// <auto-generated />

namespace MyTelegram.Schema.Channels;

/// <summary>
/// Delete all messages sent by a specific participant of a given supergroup
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 CHANNEL_INVALID The provided channel is invalid.</c></para>
/// <para><c>400 CHANNEL_PRIVATE You haven't joined this channel/supergroup.</c></para>
/// <para><c>400 CHAT_ADMIN_REQUIRED You must be an admin in this chat to do this.</c></para>
/// <para><c>403 CHAT_WRITE_FORBIDDEN You can't write in this chat.</c></para>
/// <para><c>400 MSG_ID_INVALID Invalid message ID provided.</c></para>
/// <para><c>400 PARTICIPANT_ID_INVALID The specified participant ID is invalid. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/channels.deleteParticipantHistory" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x367544db)]
public sealed partial class RequestDeleteParticipantHistory : IRequest<MyTelegram.Schema.Messages.IAffectedHistory>
{
    public uint ConstructorId => 0x367544db;

    /// <summary>
    /// Supergroup
    /// See <a href="https://corefork.telegram.org/type/InputChannel" />
    /// </summary>
    public MyTelegram.Schema.IInputChannel Channel { get; set; }

    /// <summary>
    /// The participant whose messages should be deleted
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    /// </summary>
    public MyTelegram.Schema.IInputPeer Participant { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Channel);
        writer.Write(Participant);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Channel = buffer.Read<MyTelegram.Schema.IInputChannel>();
        Participant = buffer.Read<MyTelegram.Schema.IInputPeer>();
    }
}
