// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
///See <a href="https://core.telegram.org/method/messages.getWebPagePreview" />
///</summary>
[TlObject(0x8b68b0cc)]
public sealed class RequestGetWebPagePreview : IRequest<MyTelegram.Schema.IMessageMedia>
{
    public uint ConstructorId => 0x8b68b0cc;
    public BitArray Flags { get; set; } = new BitArray(32);
    public string Message { get; set; }
    public TVector<MyTelegram.Schema.IMessageEntity>? Entities { get; set; }

    public void ComputeFlag()
    {
        if (Entities?.Count > 0) { Flags[3] = true; }
    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        bw.Serialize(Message);
        if (Flags[3]) { Entities.Serialize(bw); }
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        Message = br.Deserialize<string>();
        if (Flags[3]) { Entities = br.Deserialize<TVector<MyTelegram.Schema.IMessageEntity>>(); }
    }
}
