// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;


///<summary>
///See <a href="https://core.telegram.org/constructor/messages.historyImport" />
///</summary>
[TlObject(0x1662af0b)]
public sealed class THistoryImport : IHistoryImport
{
    public uint ConstructorId => 0x1662af0b;
    public long Id { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(Id);
    }

    public void Deserialize(BinaryReader br)
    {
        Id = br.ReadInt64();
    }
}