// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Chatlists;

///<summary>
///See <a href="https://core.telegram.org/method/chatlists.hideChatlistUpdates" />
///</summary>
[TlObject(0x66e486fb)]
public sealed class RequestHideChatlistUpdates : IRequest<IBool>
{
    public uint ConstructorId => 0x66e486fb;

    ///<summary>
    ///See <a href="https://core.telegram.org/type/InputChatlist" />
    ///</summary>
    public MyTelegram.Schema.IInputChatlist Chatlist { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Chatlist.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Chatlist = br.Deserialize<MyTelegram.Schema.IInputChatlist>();
    }
}
