// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// User is uploading a photo.
/// See <a href="https://corefork.telegram.org/constructor/sendMessageUploadPhotoAction" />
///</summary>
[TlObject(0xd1d34a26)]
public sealed class TSendMessageUploadPhotoAction : ISendMessageAction
{
    public uint ConstructorId => 0xd1d34a26;
    ///<summary>
    /// Progress percentage
    ///</summary>
    public int Progress { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Progress);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Progress = reader.ReadInt32();
    }
}