// <auto-generated />

namespace MyTelegram.Schema.Bots;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
[TlObject(0xdd1fbf93)]
public sealed partial class TAccessSettings : IAccessSettings
{
    public uint ConstructorId => 0xdd1fbf93;
    public int Flags { get; set; }

    public bool Restricted { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/User" />
    /// </summary>
    public TVector<MyTelegram.Schema.IUser>? AddUsers { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (Restricted) { flags = flags.SetBit(0); }
        if (AddUsers?.Count > 0) { flags = flags.SetBit(1); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        if (flags.IsBitSet(1)) { writer.Write(AddUsers); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Restricted = true; }
        if (Flags.IsBitSet(1)) { AddUsers = buffer.Read<TVector<MyTelegram.Schema.IUser>>(); }
    }
}
