// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/inputBotInlineResultDocument" />
///</summary>
[TlObject(0xfff8fdc4)]
public sealed class TInputBotInlineResultDocument : IInputBotInlineResult
{
    public uint ConstructorId => 0xfff8fdc4;
    public BitArray Flags { get; set; } = new BitArray(32);
    public string Id { get; set; }
    public string Type { get; set; }
    public string? Title { get; set; }
    public string? Description { get; set; }

    ///<summary>
    ///See <a href="https://core.telegram.org/type/InputDocument" />
    ///</summary>
    public MyTelegram.Schema.IInputDocument Document { get; set; }

    ///<summary>
    ///See <a href="https://core.telegram.org/type/InputBotInlineMessage" />
    ///</summary>
    public MyTelegram.Schema.IInputBotInlineMessage SendMessage { get; set; }

    public void ComputeFlag()
    {
        if (Title != null) { Flags[1] = true; }
        if (Description != null) { Flags[2] = true; }

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        bw.Serialize(Id);
        bw.Serialize(Type);
        if (Flags[1]) { bw.Serialize(Title); }
        if (Flags[2]) { bw.Serialize(Description); }
        Document.Serialize(bw);
        SendMessage.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        Id = br.Deserialize<string>();
        Type = br.Deserialize<string>();
        if (Flags[1]) { Title = br.Deserialize<string>(); }
        if (Flags[2]) { Description = br.Deserialize<string>(); }
        Document = br.Deserialize<MyTelegram.Schema.IInputDocument>();
        SendMessage = br.Deserialize<MyTelegram.Schema.IInputBotInlineMessage>();
    }
}