// <auto-generated />

namespace MyTelegram.Schema.Premium;

/// <summary>
/// Obtain which peers are we currently <a href="https://corefork.telegram.org/api/boost">boosting</a>, and how many <a href="https://corefork.telegram.org/api/boost">boost slots</a> we have left.
/// <para>See <a href="https://corefork.telegram.org/method/premium.getMyBoosts" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0xbe77b4a)]
public sealed partial class RequestGetMyBoosts : IRequest<MyTelegram.Schema.Premium.IMyBoosts>
{
    public uint ConstructorId => 0xbe77b4a;

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
