// <auto-generated />

namespace MyTelegram.Schema.Payments;

/// <summary>
/// Add or remove gifts from a <a href="https://corefork.telegram.org/api/gifts#gift-collections">star gift collection »</a>, or rename the collection.
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 PEER_ID_INVALID The provided peer id is invalid. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/payments.updateStarGiftCollection" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x4fddbee7)]
public sealed partial class RequestUpdateStarGiftCollection : IRequest<MyTelegram.Schema.IStarGiftCollection>
{
    public uint ConstructorId => 0x4fddbee7;

    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// Peer that owns the collection.
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    /// </summary>
    public MyTelegram.Schema.IInputPeer Peer { get; set; }

    /// <summary>
    /// Collection ID.
    /// </summary>
    public int CollectionId { get; set; }

    /// <summary>
    /// Title of the collection, to rename the collection.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// Can contain a list of gifts to remove from the collection.
    /// See <a href="https://corefork.telegram.org/type/InputSavedStarGift" />
    /// </summary>
    public TVector<MyTelegram.Schema.IInputSavedStarGift>? DeleteStargift { get; set; }

    /// <summary>
    /// Can contain a list of gifts to add to the collection.
    /// See <a href="https://corefork.telegram.org/type/InputSavedStarGift" />
    /// </summary>
    public TVector<MyTelegram.Schema.IInputSavedStarGift>? AddStargift { get; set; }

    /// <summary>
    /// Can contain the new gift order.
    /// See <a href="https://corefork.telegram.org/type/InputSavedStarGift" />
    /// </summary>
    public TVector<MyTelegram.Schema.IInputSavedStarGift>? Order { get; set; }

    public void ComputeFlag()
    {
        if (Title != null) { Flags = Flags.SetBit(0); }
        if (DeleteStargift?.Count > 0) { Flags = Flags.SetBit(1); }
        if (AddStargift?.Count > 0) { Flags = Flags.SetBit(2); }
        if (Order?.Count > 0) { Flags = Flags.SetBit(3); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(CollectionId);
        if (Flags.IsBitSet(0)) { writer.Write(Title); }
        if (Flags.IsBitSet(1)) { writer.Write(DeleteStargift); }
        if (Flags.IsBitSet(2)) { writer.Write(AddStargift); }
        if (Flags.IsBitSet(3)) { writer.Write(Order); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Peer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        CollectionId = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Title = buffer.ReadString(); }
        if (Flags.IsBitSet(1)) { DeleteStargift = buffer.Read<TVector<MyTelegram.Schema.IInputSavedStarGift>>(); }
        if (Flags.IsBitSet(2)) { AddStargift = buffer.Read<TVector<MyTelegram.Schema.IInputSavedStarGift>>(); }
        if (Flags.IsBitSet(3)) { Order = buffer.Read<TVector<MyTelegram.Schema.IInputSavedStarGift>>(); }
    }
}
