<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Rebus.Kafka" />-->
    <!--<PackageReference Include="Rebus.MsgPack" />-->
    <PackageReference Include="Rebus" />
    <PackageReference Include="Rebus.RabbitMq" />
    <PackageReference Include="Rebus.ServiceProvider" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyTelegram.EventBus\MyTelegram.EventBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Fody">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
