// <auto-generated />

namespace MyTelegram.Schema.Upload;

///<summary>
/// Represents the download status of a CDN file
/// See <a href="https://corefork.telegram.org/type/upload.CdnFile" />
///</summary>
[JsonDerivedType(typeof(TCdnFileReuploadNeeded), nameof(TCdnFileReuploadNeeded))]
[JsonDerivedType(typeof(TCdnFile), nameof(TCdnFile))]
public interface ICdnFile : IObject
{
}
