// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/inputInvoiceSlug" />
///</summary>
[TlObject(0xc326caef)]
public sealed class TInputInvoiceSlug : IInputInvoice
{
    public uint ConstructorId => 0xc326caef;
    public string Slug { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Slug);
    }

    public void Deserialize(BinaryReader br)
    {
        Slug = br.Deserialize<string>();
    }
}