// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/stickerSetNoCovered" />
///</summary>
[TlObject(0x77b15d1c)]
public sealed class TStickerSetNoCovered : IStickerSetCovered
{
    public uint ConstructorId => 0x77b15d1c;

    ///<summary>
    ///See <a href="https://core.telegram.org/type/StickerSet" />
    ///</summary>
    public MyTelegram.Schema.IStickerSet Set { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Set.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Set = br.Deserialize<MyTelegram.Schema.IStickerSet>();
    }
}