// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/messageActionTopicCreate" />
///</summary>
[TlObject(0xd999256)]
public sealed class TMessageActionTopicCreate : IMessageAction
{
    public uint ConstructorId => 0xd999256;
    public BitArray Flags { get; set; } = new BitArray(32);
    public string Title { get; set; }
    public int IconColor { get; set; }
    public long? IconEmojiId { get; set; }

    public void ComputeFlag()
    {
        if (IconEmojiId != 0 && IconEmojiId.HasValue) { Flags[0] = true; }
    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        bw.Serialize(Title);
        bw.Write(IconColor);
        if (Flags[0]) { bw.Write(IconEmojiId.Value); }
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        Title = br.Deserialize<string>();
        IconColor = br.ReadInt32();
        if (Flags[0]) { IconEmojiId = br.ReadInt64(); }
    }
}