// <auto-generated />

namespace MyTelegram.Schema.Account.LayerN;

/// <summary>
/// Register device to receive <a href="https://corefork.telegram.org/api/push-updates">PUSH notifications</a>
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 TOKEN_EMPTY The specified token is empty.</c></para>
/// <para><c>400 TOKEN_INVALID The provided token is invalid.</c></para>
/// <para><c>400 TOKEN_TYPE_INVALID The specified token type is invalid.</c></para>
/// <para><c>400 WEBPUSH_AUTH_INVALID The specified web push authentication secret is invalid.</c></para>
/// <para><c>400 WEBPUSH_KEY_INVALID The specified web push elliptic curve Diffie-Hellman public key is invalid.</c></para>
/// <para><c>400 WEBPUSH_TOKEN_INVALID The specified web push token is invalid. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/account.registerDevice" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x637ea878)]
public sealed partial class RequestRegisterDevice : IRequest<IBool>, ILayeredData
{
    public uint ConstructorId => 0x637ea878;

    public int Layer => -666;

    /// <summary>
    /// Device token type, see <a href="https://corefork.telegram.org/api/push-updates#subscribing-to-notifications">PUSH updates</a> for the possible values.
    /// </summary>
    public int TokenType { get; set; }

    /// <summary>
    /// Device token, see <a href="https://corefork.telegram.org/api/push-updates#subscribing-to-notifications">PUSH updates</a> for the possible values.
    /// </summary>
    public string Token { get; set; }


    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(TokenType);
        writer.Write(Token);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        TokenType = buffer.ReadInt32();
        Token = buffer.ReadString();
    }
}
