<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EventFlow" />
    <!--<ProjectReference Include="..\EventFlow\EventFlow.csproj" />-->
    <ProjectReference Include="..\MyTelegram.Domain.Shared\MyTelegram.Domain.Shared.csproj" />
        <ProjectReference Include="..\MyTelegram.EventFlow\MyTelegram.EventFlow.csproj" />
    <ProjectReference Include="..\MyTelegram.Schema\MyTelegram.Schema.csproj" />
    <ProjectReference Include="..\MyTelegram.SourceGenerators\MyTelegram.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Fody">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
