global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Hosting;
global using MyTelegram.Core;
global using Volo.Abp;
global using Volo.Abp.Caching;
global using Volo.Abp.Caching.StackExchangeRedis;
global using Volo.Abp.EventBus.Distributed;
global using Volo.Abp.EventBus.RabbitMq;
global using Volo.Abp.Modularity;