// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/updateBotChatInviteRequester" />
///</summary>
[TlObject(0x11dfa986)]
public class TUpdateBotChatInviteRequester : IUpdate
{
    public uint ConstructorId => 0x11dfa986;

    ///<summary>
    ///See <a href="https://core.telegram.org/type/Peer" />
    ///</summary>
    public MyTelegram.Schema.IPeer Peer { get; set; }
    public int Date { get; set; }
    public long UserId { get; set; }
    public string About { get; set; }

    ///<summary>
    ///See <a href="https://core.telegram.org/type/ExportedChatInvite" />
    ///</summary>
    public MyTelegram.Schema.IExportedChatInvite Invite { get; set; }
    public int Qts { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Peer.Serialize(bw);
        bw.Write(Date);
        bw.Write(UserId);
        bw.Serialize(About);
        Invite.Serialize(bw);
        bw.Write(Qts);
    }

    public void Deserialize(BinaryReader br)
    {
        Peer = br.Deserialize<MyTelegram.Schema.IPeer>();
        Date = br.ReadInt32();
        UserId = br.ReadInt64();
        About = br.Deserialize<string>();
        Invite = br.Deserialize<MyTelegram.Schema.IExportedChatInvite>();
        Qts = br.ReadInt32();
    }
}