// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/statsAbsValueAndPrev" />
///</summary>
[TlObject(0xcb43acde)]
public class TStatsAbsValueAndPrev : IStatsAbsValueAndPrev
{
    public uint ConstructorId => 0xcb43acde;
    public double Current { get; set; }
    public double Previous { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Current);
        bw.Serialize(Previous);
    }

    public void Deserialize(BinaryReader br)
    {
        Current = br.ReadDouble();
        Previous = br.ReadDouble();
    }
}