// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/updatePinnedChannelMessages" />
///</summary>
[TlObject(0x5bb98608)]
public sealed class TUpdatePinnedChannelMessages : IUpdate
{
    public uint ConstructorId => 0x5bb98608;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Pinned { get; set; }
    public long ChannelId { get; set; }
    public TVector<int> Messages { get; set; }
    public int Pts { get; set; }
    public int PtsCount { get; set; }

    public void ComputeFlag()
    {
        if (Pinned) { Flags[0] = true; }

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        bw.Write(ChannelId);
        Messages.Serialize(bw);
        bw.Write(Pts);
        bw.Write(PtsCount);
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        if (Flags[0]) { Pinned = true; }
        ChannelId = br.ReadInt64();
        Messages = br.Deserialize<TVector<int>>();
        Pts = br.ReadInt32();
        PtsCount = br.ReadInt32();
    }
}