global using EventFlow;
global using EventFlow.Extensions;
global using EventFlow.MongoDB.ReadStores;
global using EventFlow.Queries;
global using MongoDB.Driver;
global using MyTelegram.ReadModel.Interfaces;
global using MyTelegram.Domain.Aggregates.Channel;
global using MyTelegram.Domain.Aggregates.Contact;
global using MyTelegram.EventFlow.ReadStores;
global using MyTelegram.Queries;
global using System.Linq.Expressions;
global using AccessHashReadModel = MyTelegram.ReadModel.MongoDB.AccessHashReadModel;
global using AppCodeReadModel = MyTelegram.ReadModel.MongoDB.AppCodeReadModel;
//global using BotReadModel = MyTelegram.ReadModel.MongoDB.BotReadModel;
global using ChannelFullReadModel = MyTelegram.ReadModel.MongoDB.ChannelFullReadModel;
global using ChannelMemberReadModel = MyTelegram.ReadModel.MongoDB.ChannelMemberReadModel;
global using ChannelReadModel = MyTelegram.ReadModel.MongoDB.ChannelReadModel;
global using ChatAdminReadModel = MyTelegram.ReadModel.MongoDB.ChatAdminReadModel;
global using ChatInviteImporterReadModel = MyTelegram.ReadModel.MongoDB.ChatInviteImporterReadModel;
global using ChatInviteReadModel = MyTelegram.ReadModel.MongoDB.ChatInviteReadModel;
global using ContactReadModel = MyTelegram.ReadModel.MongoDB.ContactReadModel;
global using DeviceReadModel = MyTelegram.ReadModel.MongoDB.DeviceReadModel;
global using DialogFilterReadModel = MyTelegram.ReadModel.MongoDB.DialogFilterReadModel;
global using DialogReadModel = MyTelegram.ReadModel.MongoDB.DialogReadModel;
global using DraftReadModel = MyTelegram.ReadModel.MongoDB.DraftReadModel;
global using LanguageReadModel = MyTelegram.ReadModel.MongoDB.LanguageReadModel;
global using LanguageTextReadModel = MyTelegram.ReadModel.MongoDB.LanguageTextReadModel;
global using MessageReadModel = MyTelegram.ReadModel.MongoDB.MessageReadModel;
global using PeerNotifySettingsReadModel = MyTelegram.ReadModel.MongoDB.PeerNotifySettingsReadModel;
global using PeerSettingsReadModel = MyTelegram.ReadModel.MongoDB.PeerSettingsReadModel;
global using PhotoReadModel = MyTelegram.ReadModel.MongoDB.PhotoReadModel;
global using PollAnswerVoterReadModel = MyTelegram.ReadModel.MongoDB.PollAnswerVoterReadModel;
global using PollReadModel = MyTelegram.ReadModel.MongoDB.PollReadModel;
global using PtsForAuthKeyIdReadModel = MyTelegram.ReadModel.MongoDB.PtsForAuthKeyIdReadModel;
global using PtsReadModel = MyTelegram.ReadModel.MongoDB.PtsReadModel;
//global using PushUpdatesReadModel = MyTelegram.ReadModel.MongoDB.PushUpdatesReadModel;
global using ReadingHistoryReadModel = MyTelegram.ReadModel.MongoDB.ReadingHistoryReadModel;
global using ReplyReadModel = MyTelegram.ReadModel.MongoDB.ReplyReadModel;
global using RpcResultReadModel = MyTelegram.ReadModel.MongoDB.RpcResultReadModel;
global using UpdatesReadModel = MyTelegram.ReadModel.MongoDB.UpdatesReadModel;
global using UserNameReadModel = MyTelegram.ReadModel.MongoDB.UserNameReadModel;
global using UserReadModel = MyTelegram.ReadModel.MongoDB.UserReadModel;
global using JoinChannelRequestReadModel=MyTelegram.ReadModel.MongoDB.JoinChannelRequestReadModel;
global using UserConfigReadModel = MyTelegram.ReadModel.MongoDB.UserConfigReadModel;
global using MessageTokenReadModel = MyTelegram.ReadModel.MongoDB.MessageTokenReadModel;