// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/shippingOption" />
///</summary>
[TlObject(0xb6213cdf)]
public sealed class TShippingOption : IShippingOption
{
    public uint ConstructorId => 0xb6213cdf;
    public string Id { get; set; }
    public string Title { get; set; }
    public TVector<MyTelegram.Schema.ILabeledPrice> Prices { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Id);
        bw.Serialize(Title);
        Prices.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Id = br.Deserialize<string>();
        Title = br.Deserialize<string>();
        Prices = br.Deserialize<TVector<MyTelegram.Schema.ILabeledPrice>>();
    }
}