// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Auth;

///<summary>
/// The next time, the authentication code will be delivered via an immediately canceled incoming call.
/// See <a href="https://corefork.telegram.org/constructor/auth.codeTypeFlashCall" />
///</summary>
[TlObject(0x226ccefb)]
public sealed class TCodeTypeFlashCall : ICodeType
{
    public uint ConstructorId => 0x226ccefb;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}