// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// Privacy rules
/// See <a href="https://corefork.telegram.org/constructor/account.privacyRules" />
///</summary>
[TlObject(0x50a04e45)]
public sealed class TPrivacyRules : IPrivacyRules
{
    public uint ConstructorId => 0x50a04e45;
    ///<summary>
    /// Privacy rules
    ///</summary>
    public TVector<MyTelegram.Schema.IPrivacyRule> Rules { get; set; }

    ///<summary>
    /// Chats to which the rules apply
    ///</summary>
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }

    ///<summary>
    /// Users to which the rules apply
    ///</summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Rules);
        writer.Write(Chats);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Rules = reader.Read<TVector<MyTelegram.Schema.IPrivacyRule>>();
        Chats = reader.Read<TVector<MyTelegram.Schema.IChat>>();
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}