// <auto-generated />

namespace MyTelegram.Schema.Communities;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// Access: [User ] [Bot ] [Anonymous ]
/// </remarks>
[TlObject(0xd766e3ea)]
public sealed partial class RequestToggleCommunityCollapsedInDialogs : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xd766e3ea;

    public int Flags { get; set; }

    public bool Collapsed { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputChannel" />
    /// </summary>
    public MyTelegram.Schema.IInputChannel Community { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (Collapsed) { flags = flags.SetBit(0); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        writer.Write(Community);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Collapsed = true; }
        Community = buffer.Read<MyTelegram.Schema.IInputChannel>();
    }
}
