// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// Access: [User ] [Bot ] [Anonymous ]
/// </remarks>
[TlObject(0x56655768)]
public sealed partial class RequestGetWebBrowserSettings : IRequest<MyTelegram.Schema.Account.IWebBrowserSettings>
{
    public uint ConstructorId => 0x56655768;

    public long Hash { get; set; }


    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Hash = buffer.ReadInt64();
    }
}
