// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// Clears list of recently used <a href="https://corefork.telegram.org/api/emoji-status">emoji statuses</a>
/// <para>See <a href="https://corefork.telegram.org/method/account.clearRecentEmojiStatuses" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x18201aae)]
public sealed partial class RequestClearRecentEmojiStatuses : IRequest<IBool>
{
    public uint ConstructorId => 0x18201aae;

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
