// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// Resets all notification settings from users and groups.
/// <para>See <a href="https://corefork.telegram.org/method/account.resetNotifySettings" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0xdb7e1747)]
public sealed partial class RequestResetNotifySettings : IRequest<IBool>
{
    public uint ConstructorId => 0xdb7e1747;

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
