// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// Get the current <a href="https://corefork.telegram.org/api/reactions#notifications-about-reactions">reaction notification settings »</a>.
/// <para>See <a href="https://corefork.telegram.org/method/account.getReactionsNotifySettings" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x6dd654c)]
public sealed partial class RequestGetReactionsNotifySettings : IRequest<MyTelegram.Schema.IReactionsNotifySettings>
{
    public uint ConstructorId => 0x6dd654c;

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
