// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// Access: [User ] [Bot ] [Anonymous ]
/// </remarks>
[TlObject(0x60ed4229)]
public sealed partial class RequestToggleWebBrowserSettingsException : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x60ed4229;

    public int Flags { get; set; }

    public bool Delete { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/Bool" />
    /// </summary>
    public bool? OpenExternalBrowser { get; set; }

    public string Url { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (Delete) { flags = flags.SetBit(1); }
        if (OpenExternalBrowser != null) { flags = flags.SetBit(0); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        if (flags.IsBitSet(0)) { writer.Write(OpenExternalBrowser.Value); }
        writer.Write(Url);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(1)) { Delete = true; }
        if (Flags.IsBitSet(0)) { OpenExternalBrowser = buffer.Read(); }
        Url = buffer.ReadString();
    }
}
