// <auto-generated />

namespace MyTelegram.Schema.Account;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// Access: [User ] [Bot ] [Anonymous ]
/// </remarks>
[TlObject(0x55b41fd6)]
public sealed partial class RequestRegisterPasskey : IRequest<MyTelegram.Schema.IPasskey>
{
    public uint ConstructorId => 0x55b41fd6;

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputPasskeyCredential" />
    /// </summary>
    public MyTelegram.Schema.IInputPasskeyCredential Credential { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Credential);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Credential = buffer.Read<MyTelegram.Schema.IInputPasskeyCredential>();
    }
}
