// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
[TlObject(0x310240cc)]
public sealed partial class TAuctionBidLevel : IAuctionBidLevel
{
    public uint ConstructorId => 0x310240cc;
    public int Pos { get; set; }

    public long Amount { get; set; }

    public int Date { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Pos);
        writer.Write(Amount);
        writer.Write(Date);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Pos = buffer.ReadInt32();
        Amount = buffer.ReadInt64();
        Date = buffer.ReadInt32();
    }
}
