// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Day theme
/// <para>See <a href="https://corefork.telegram.org/constructor/baseThemeDay" /></para>
/// </summary>
[TlObject(0xfbd81688)]
public sealed partial class TBaseThemeDay : IBaseTheme
{
    public uint ConstructorId => 0xfbd81688;

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
