// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Specifies the chats that <strong>can</strong> receive Telegram Business <a href="https://corefork.telegram.org/api/business#away-messages">away »</a> and <a href="https://corefork.telegram.org/api/business#greeting-messages">greeting »</a> messages.If <code>exclude_selected</code> is set, specifies all chats that <strong>cannot</strong> receive Telegram Business <a href="https://corefork.telegram.org/api/business#away-messages">away »</a> and <a href="https://corefork.telegram.org/api/business#greeting-messages">greeting »</a> messages.
/// <para>See <a href="https://corefork.telegram.org/constructor/inputBusinessRecipients" /></para>
/// </summary>
[TlObject(0x6f8b32aa)]
public sealed partial class TInputBusinessRecipients : IInputBusinessRecipients
{
    public uint ConstructorId => 0x6f8b32aa;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// All existing private chats.
    /// </summary>
    public bool ExistingChats { get; set; }

    /// <summary>
    /// All new private chats.
    /// </summary>
    public bool NewChats { get; set; }

    /// <summary>
    /// All private chats with contacts.
    /// </summary>
    public bool Contacts { get; set; }

    /// <summary>
    /// All private chats with non-contacts.
    /// </summary>
    public bool NonContacts { get; set; }

    /// <summary>
    /// If set, inverts the selection.
    /// </summary>
    public bool ExcludeSelected { get; set; }

    /// <summary>
    /// Only private chats with the specified users.
    /// See <a href="https://corefork.telegram.org/type/InputUser" />
    /// </summary>
    public TVector<MyTelegram.Schema.IInputUser>? Users { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (ExistingChats) { flags = flags.SetBit(0); }
        if (NewChats) { flags = flags.SetBit(1); }
        if (Contacts) { flags = flags.SetBit(2); }
        if (NonContacts) { flags = flags.SetBit(3); }
        if (ExcludeSelected) { flags = flags.SetBit(5); }
        if (Users?.Count > 0) { flags = flags.SetBit(4); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        if (flags.IsBitSet(4)) { writer.Write(Users); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { ExistingChats = true; }
        if (Flags.IsBitSet(1)) { NewChats = true; }
        if (Flags.IsBitSet(2)) { Contacts = true; }
        if (Flags.IsBitSet(3)) { NonContacts = true; }
        if (Flags.IsBitSet(5)) { ExcludeSelected = true; }
        if (Flags.IsBitSet(4)) { Users = buffer.Read<TVector<MyTelegram.Schema.IInputUser>>(); }
    }
}
