// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
[TlObject(0x3c27b78f)]
public sealed partial class TInputPasskeyCredentialPublicKey : IInputPasskeyCredential
{
    public uint ConstructorId => 0x3c27b78f;
    public string Id { get; set; }

    public string RawId { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputPasskeyResponse" />
    /// </summary>
    public MyTelegram.Schema.IInputPasskeyResponse Response { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Id);
        writer.Write(RawId);
        writer.Write(Response);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Id = buffer.ReadString();
        RawId = buffer.ReadString();
        Response = buffer.Read<MyTelegram.Schema.IInputPasskeyResponse>();
    }
}
