// <auto-generated />

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputMediaTodo" />
///</summary>
[TlObject(0x9fc55fde)]
public sealed class TInputMediaTodo : IInputMedia
{
    public uint ConstructorId => 0x9fc55fde;
    ///<summary>
    /// See <a href="https://corefork.telegram.org/type/TodoList" />
    ///</summary>
    public MyTelegram.Schema.ITodoList Todo { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Todo);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Todo = buffer.Read<MyTelegram.Schema.ITodoList>();
    }
}
