// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/inputStarGiftAuctionSlug" /></para>
/// </summary>
[TlObject(0x7ab58308)]
public sealed partial class TInputStarGiftAuctionSlug : IInputStarGiftAuction
{
    public uint ConstructorId => 0x7ab58308;
    /// <summary>
    ///  
    /// </summary>
    public string Slug { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Slug);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Slug = buffer.ReadString();
    }
}
