// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// An <a href="https://corefork.telegram.org/api/gifts#collectible-gifts">owned collectible gift »</a> as emoji status: can only be used in <a href="https://corefork.telegram.org/method/account.updateEmojiStatus">account.updateEmojiStatus</a>, is never returned by the API.Note that once set, the status will be returned to users as a <a href="https://corefork.telegram.org/constructor/emojiStatusCollectible">emojiStatusCollectible</a> constructor, instead (which <strong>cannot</strong> be passed to <a href="https://corefork.telegram.org/method/account.updateEmojiStatus">account.updateEmojiStatus</a>, and must be converted to an <a href="https://corefork.telegram.org/constructor/inputEmojiStatusCollectible">inputEmojiStatusCollectible</a> first).
/// <para>See <a href="https://corefork.telegram.org/constructor/inputEmojiStatusCollectible" /></para>
/// </summary>
[TlObject(0x7141dbf)]
public sealed partial class TInputEmojiStatusCollectible : IEmojiStatus
{
    public uint ConstructorId => 0x7141dbf;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// ID of the collectible (from <a href="https://corefork.telegram.org/constructor/starGiftUnique">starGiftUnique</a>.<code>id</code>).
    /// </summary>
    public long CollectibleId { get; set; }

    /// <summary>
    /// If set, the emoji status will be active until the specified unixtime.
    /// </summary>
    public int? Until { get; set; }

    public void ComputeFlag()
    {
        if (/*Until != 0 && */Until.HasValue) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(CollectibleId);
        if (Flags.IsBitSet(0)) { writer.Write(Until.Value); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        CollectibleId = buffer.ReadInt64();
        if (Flags.IsBitSet(0)) { Until = buffer.ReadInt32(); }
    }
}
