// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Stickers to show when receiving a gifted Telegram Premium subscription
/// <para>See <a href="https://corefork.telegram.org/constructor/inputStickerSetPremiumGifts" /></para>
/// </summary>
[TlObject(0xc88b3b02)]
public sealed partial class TInputStickerSetPremiumGifts : IInputStickerSet
{
    public uint ConstructorId => 0xc88b3b02;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
