// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
[TlObject(0x9961bcb4)]
public sealed partial class TInputInlineButtonTypeUrlAuth : IInlineButtonType
{
    public uint ConstructorId => 0x9961bcb4;
    public int Flags { get; set; }

    public bool RequestWriteAccess { get; set; }

    public string? FwdText { get; set; }

    public string Url { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputUser" />
    /// </summary>
    public MyTelegram.Schema.IInputUser? Bot { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (RequestWriteAccess) { flags = flags.SetBit(0); }
        if (FwdText != null) { flags = flags.SetBit(1); }
        if (Bot != null) { flags = flags.SetBit(2); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        if (flags.IsBitSet(1)) { writer.Write(FwdText); }
        writer.Write(Url);
        if (flags.IsBitSet(2)) { writer.Write(Bot); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { RequestWriteAccess = true; }
        if (Flags.IsBitSet(1)) { FwdText = buffer.ReadString(); }
        Url = buffer.ReadString();
        if (Flags.IsBitSet(2)) { Bot = buffer.Read<MyTelegram.Schema.IInputUser>(); }
    }
}
