// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// All <a href="https://corefork.telegram.org/api/channel">channels</a>
/// <para>See <a href="https://corefork.telegram.org/constructor/inputNotifyBroadcasts" /></para>
/// </summary>
[TlObject(0xb1db7c7e)]
public sealed partial class TInputNotifyBroadcasts : IInputNotifyPeer
{
    public uint ConstructorId => 0xb1db7c7e;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
