// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
[TlObject(0xae152a69)]
public sealed partial class TJoinChatBotResultApproved : IJoinChatBotResult
{
    public uint ConstructorId => 0xae152a69;

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
