// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
[TlObject(0x4a8bfe80)]
public sealed partial class TMessageActionChatJoinedViaCommunity : IMessageAction
{
    public uint ConstructorId => 0x4a8bfe80;
    public long CommunityId { get; set; }


    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
        writer.Write(CommunityId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        CommunityId = buffer.ReadInt64();
    }
}
