// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Group profile photo removed.
/// <para>See <a href="https://corefork.telegram.org/constructor/messageActionChatDeletePhoto" /></para>
/// </summary>
[TlObject(0x95e3fbef)]
public sealed partial class TMessageActionChatDeletePhoto : IMessageAction
{
    public uint ConstructorId => 0x95e3fbef;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
