// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Table
/// <para>See <a href="https://corefork.telegram.org/constructor/pageBlockTable" /></para>
/// </summary>
[TlObject(0xbf4dea82)]
public sealed partial class TPageBlockTable : IPageBlock
{
    public uint ConstructorId => 0xbf4dea82;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// Does the table have a visible border?
    /// </summary>
    public bool Bordered { get; set; }

    /// <summary>
    /// Is the table striped?
    /// </summary>
    public bool Striped { get; set; }

    public bool Compact { get; set; }

    /// <summary>
    /// Title
    /// See <a href="https://corefork.telegram.org/type/RichText" />
    /// </summary>
    public MyTelegram.Schema.IRichText Title { get; set; }

    /// <summary>
    /// Table rows
    /// See <a href="https://corefork.telegram.org/type/PageTableRow" />
    /// </summary>
    public TVector<MyTelegram.Schema.IPageTableRow> Rows { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (Bordered) { flags = flags.SetBit(0); }
        if (Striped) { flags = flags.SetBit(1); }
        if (Compact) { flags = flags.SetBit(2); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        writer.Write(Title);
        writer.Write(Rows);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Bordered = true; }
        if (Flags.IsBitSet(1)) { Striped = true; }
        if (Flags.IsBitSet(2)) { Compact = true; }
        Title = buffer.Read<MyTelegram.Schema.IRichText>();
        Rows = buffer.Read<TVector<MyTelegram.Schema.IPageTableRow>>();
    }
}
