// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// The phone call was missed
/// <para>See <a href="https://corefork.telegram.org/constructor/phoneCallDiscardReasonMissed" /></para>
/// </summary>
[TlObject(0x85e42301)]
public sealed partial class TPhoneCallDiscardReasonMissed : IPhoneCallDiscardReason
{
    public uint ConstructorId => 0x85e42301;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
