// <auto-generated />

namespace MyTelegram.Schema;

///<summary>
/// Allow bots and mini apps
/// See <a href="https://corefork.telegram.org/constructor/privacyValueAllowBots" />
///</summary>
[TlObject(0x21461b5d)]
public sealed class TPrivacyValueAllowBots : IPrivacyRule
{
    public uint ConstructorId => 0x21461b5d;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
