// <auto-generated />

namespace MyTelegram.Schema;

///<summary>
/// Represents a <a href="https://corefork.telegram.org/api/reactions#paid-reactions">paid Telegram Star reaction »</a>.
/// See <a href="https://corefork.telegram.org/constructor/reactionPaid" />
///</summary>
[TlObject(0x523da4eb)]
public sealed class TReactionPaid : IReaction
{
    public uint ConstructorId => 0x523da4eb;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
