// <auto-generated />

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsTonAmount" />
///</summary>
[TlObject(0x74aee3e0)]
public sealed class TStarsTonAmount : IStarsAmount
{
    public uint ConstructorId => 0x74aee3e0;
    public long Amount { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Amount);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Amount = buffer.ReadInt64();
    }
}
