// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// The ID of a pattern of a <a href="https://corefork.telegram.org/api/gifts#collectible-gifts">collectible gift »</a>.
/// <para>See <a href="https://corefork.telegram.org/constructor/starGiftAttributeIdPattern" /></para>
/// </summary>
[TlObject(0x4a162433)]
public sealed partial class TStarGiftAttributeIdPattern : IStarGiftAttributeId
{
    public uint ConstructorId => 0x4a162433;
    /// <summary>
    /// The <a href="https://corefork.telegram.org/api/stickers">sticker</a> representing the symbol
    /// </summary>
    public long DocumentId { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(DocumentId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        DocumentId = buffer.ReadInt64();
    }
}
