// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Represents the profile's <a href="https://corefork.telegram.org/api/stars#star-rating">star rating, see here »</a> for more info.
/// <para>See <a href="https://corefork.telegram.org/constructor/starsRating" /></para>
/// </summary>
[TlObject(0x1b0e4f07)]
public sealed partial class TStarsRating : IStarsRating
{
    public uint ConstructorId => 0x1b0e4f07;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// The current level, may be negative.
    /// </summary>
    public int Level { get; set; }

    /// <summary>
    /// The numerical value of the rating required for the current level.
    /// </summary>
    public long CurrentLevelStars { get; set; }

    /// <summary>
    /// Numerical value of the current rating.
    /// </summary>
    public long Stars { get; set; }

    /// <summary>
    /// The numerical value of the rating required for the next level.
    /// </summary>
    public long? NextLevelStars { get; set; }

    public void ComputeFlag()
    {
        if (/*NextLevelStars != 0 &&*/ NextLevelStars.HasValue) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Level);
        writer.Write(CurrentLevelStars);
        writer.Write(Stars);
        if (Flags.IsBitSet(0)) { writer.Write(NextLevelStars.Value); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Level = buffer.ReadInt32();
        CurrentLevelStars = buffer.ReadInt64();
        Stars = buffer.ReadInt64();
        if (Flags.IsBitSet(0)) { NextLevelStars = buffer.ReadInt64(); }
    }
}
