// <auto-generated />

namespace MyTelegram.Schema;

///<summary>
/// The list of <a href="https://corefork.telegram.org/api/saved-messages#tags">reaction tag »</a> names assigned by the user has changed and should be refetched using <a href="https://corefork.telegram.org/method/messages.getSavedReactionTags">messages.getSavedReactionTags »</a>.
/// See <a href="https://corefork.telegram.org/constructor/updateSavedReactionTags" />
///</summary>
[TlObject(0x39c67432)]
public sealed class TUpdateSavedReactionTags : IUpdate
{
    public uint ConstructorId => 0x39c67432;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
