// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// An admin has (un)exempted this <a href="https://corefork.telegram.org/api/monoforum">monoforum topic »</a> from payment to send messages using <a href="https://corefork.telegram.org/method/account.toggleNoPaidMessagesException">account.toggleNoPaidMessagesException</a>.
/// <para>See <a href="https://corefork.telegram.org/constructor/updateMonoForumNoPaidException" /></para>
/// </summary>
[TlObject(0x9f812b08)]
public sealed partial class TUpdateMonoForumNoPaidException : IUpdate
{
    public uint ConstructorId => 0x9f812b08;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// If set, an admin has exempted this peer, otherwise the peer was unexempted.
    /// </summary>
    public bool Exception { get; set; }

    /// <summary>
    /// The monoforum ID.
    /// </summary>
    public long ChannelId { get; set; }

    /// <summary>
    /// The peer/topic ID.
    /// See <a href="https://corefork.telegram.org/type/Peer" />
    /// </summary>
    public MyTelegram.Schema.IPeer SavedPeerId { get; set; }

    public void ComputeFlag()
    {
        if (Exception) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(ChannelId);
        writer.Write(SavedPeerId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Exception = true; }
        ChannelId = buffer.ReadInt64();
        SavedPeerId = buffer.Read<MyTelegram.Schema.IPeer>();
    }
}
