// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Page theme
/// <para>See <a href="https://corefork.telegram.org/constructor/webPageAttributeTheme" /></para>
/// </summary>
[TlObject(0x54b56617)]
public sealed partial class TWebPageAttributeTheme : IWebPageAttribute
{
    public uint ConstructorId => 0x54b56617;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// Theme files
    /// See <a href="https://corefork.telegram.org/type/Document" />
    /// </summary>
    public TVector<MyTelegram.Schema.IDocument>? Documents { get; set; }

    /// <summary>
    /// Theme settings
    /// See <a href="https://corefork.telegram.org/type/ThemeSettings" />
    /// </summary>
    public MyTelegram.Schema.IThemeSettings? Settings { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (Documents?.Count > 0) { flags = flags.SetBit(0); }
        if (Settings != null) { flags = flags.SetBit(1); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        if (flags.IsBitSet(0)) { writer.Write(Documents); }
        if (flags.IsBitSet(1)) { writer.Write(Settings); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Documents = buffer.Read<TVector<MyTelegram.Schema.IDocument>>(); }
        if (Flags.IsBitSet(1)) { Settings = buffer.Read<MyTelegram.Schema.IThemeSettings>(); }
    }
}
