// <auto-generated />
namespace MyTelegram.Messenger.Handlers.Messages;
/// <summary>
/// <para><c>See <a href="https://corefork.telegram.org/method/messages.deleteTopicHistory"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✖] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class DeleteTopicHistoryHandler : RpcResultObjectHandler<MyTelegram.Schema.Messages.RequestDeleteTopicHistory, MyTelegram.Schema.Messages.IAffectedHistory>, IObjectHandler
{
    protected override Task<MyTelegram.Schema.Messages.IAffectedHistory> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Messages.RequestDeleteTopicHistory obj)
    {
        throw new NotImplementedException();
    }
}