// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// Get featured stickers
/// <para>See <a href="https://corefork.telegram.org/method/messages.getFeaturedStickers" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x64780b14)]
public sealed partial class RequestGetFeaturedStickers : IRequest<MyTelegram.Schema.Messages.IFeaturedStickers>
{
    public uint ConstructorId => 0x64780b14;

    /// <summary>
    /// <a href="https://corefork.telegram.org/api/offsets#hash-generation">Hash used for caching, for more info click here</a>.
    /// </summary>
    public long Hash { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Hash = buffer.ReadInt64();
    }
}
