// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// Gets the default value of the Time-To-Live setting, applied to all new chats.
/// See <a href="https://corefork.telegram.org/method/messages.getDefaultHistoryTTL" />
///</summary>
[TlObject(0x658b7188)]
public sealed class RequestGetDefaultHistoryTTL : IRequest<MyTelegram.Schema.IDefaultHistoryTTL>
{
    public uint ConstructorId => 0x658b7188;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}
