// <auto-generated />

namespace MyTelegram.Schema.Messages;

///<summary>
/// Fetch a default recommended list of <a href="https://corefork.telegram.org/api/saved-messages#tags">saved message tag reactions</a>.
/// See <a href="https://corefork.telegram.org/method/messages.getDefaultTagReactions" />
///</summary>
[TlObject(0xbdf93428)]
public sealed class RequestGetDefaultTagReactions : IRequest<MyTelegram.Schema.Messages.IReactions>
{
    public uint ConstructorId => 0xbdf93428;

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/offsets#hash-generation">Hash used for caching, for more info click here</a>.
    ///</summary>
    public long Hash { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Hash = buffer.ReadInt64();
    }
}
