// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// Search for messages and peers globally
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 FOLDER_ID_INVALID Invalid folder ID.</c></para>
/// <para><c>400 INPUT_FILTER_INVALID The specified filter is invalid.</c></para>
/// <para><c>400 SEARCH_QUERY_EMPTY The search query is empty. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/messages.searchGlobal" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0x6126a43c)]
public sealed partial class RequestSearchGlobal : IRequest<MyTelegram.Schema.Messages.IMessages>
{
    public uint ConstructorId => 0x6126a43c;

    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// If set, only returns results from channels (used in the <a href="https://corefork.telegram.org/api/search#global-search">global channel search tab »</a>).
    /// </summary>
    public bool BroadcastsOnly { get; set; }

    /// <summary>
    /// Whether to search only in groups
    /// </summary>
    public bool GroupsOnly { get; set; }

    /// <summary>
    /// Whether to search only in private chats
    /// </summary>
    public bool UsersOnly { get; set; }

    /// <summary>
    /// <a href="https://corefork.telegram.org/api/folders#peer-folders">Peer folder ID, for more info click here</a>
    /// </summary>
    public int? FolderId { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputChannel" />
    /// </summary>
    public MyTelegram.Schema.IInputChannel? Community { get; set; }

    /// <summary>
    /// Query
    /// </summary>
    public string Q { get; set; }

    /// <summary>
    /// Global search filter
    /// See <a href="https://corefork.telegram.org/type/MessagesFilter" />
    /// </summary>
    public MyTelegram.Schema.IMessagesFilter Filter { get; set; }

    /// <summary>
    /// If a positive value was specified, the method will return only messages with date bigger than min_date
    /// </summary>
    public int MinDate { get; set; }

    /// <summary>
    /// If a positive value was transferred, the method will return only messages with date smaller than max_date
    /// </summary>
    public int MaxDate { get; set; }

    /// <summary>
    /// Initially 0, then set to the <a href="https://corefork.telegram.org/constructor/messages.messagesSlice"><code>next_rate</code> parameter of messages.messagesSlice</a>, or if that is absent, the <code>date</code> of the last returned message.
    /// </summary>
    public int OffsetRate { get; set; }

    /// <summary>
    /// <a href="https://corefork.telegram.org/api/offsets">Offsets for pagination, for more info click here</a>
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    /// </summary>
    public MyTelegram.Schema.IInputPeer OffsetPeer { get; set; }

    /// <summary>
    /// <a href="https://corefork.telegram.org/api/offsets">Offsets for pagination, for more info click here</a>
    /// </summary>
    public int OffsetId { get; set; }

    /// <summary>
    /// <a href="https://corefork.telegram.org/api/offsets">Offsets for pagination, for more info click here</a>
    /// </summary>
    public int Limit { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (BroadcastsOnly) { flags = flags.SetBit(1); }
        if (GroupsOnly) { flags = flags.SetBit(2); }
        if (UsersOnly) { flags = flags.SetBit(3); }
        if (/*FolderId != 0 && */FolderId.HasValue) { flags = flags.SetBit(0); }
        if (Community != null) { flags = flags.SetBit(4); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        if (flags.IsBitSet(0)) { writer.Write(FolderId.Value); }
        if (flags.IsBitSet(4)) { writer.Write(Community); }
        writer.Write(Q);
        writer.Write(Filter);
        writer.Write(MinDate);
        writer.Write(MaxDate);
        writer.Write(OffsetRate);
        writer.Write(OffsetPeer);
        writer.Write(OffsetId);
        writer.Write(Limit);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(1)) { BroadcastsOnly = true; }
        if (Flags.IsBitSet(2)) { GroupsOnly = true; }
        if (Flags.IsBitSet(3)) { UsersOnly = true; }
        if (Flags.IsBitSet(0)) { FolderId = buffer.ReadInt32(); }
        if (Flags.IsBitSet(4)) { Community = buffer.Read<MyTelegram.Schema.IInputChannel>(); }
        Q = buffer.ReadString();
        Filter = buffer.Read<MyTelegram.Schema.IMessagesFilter>();
        MinDate = buffer.ReadInt32();
        MaxDate = buffer.ReadInt32();
        OffsetRate = buffer.ReadInt32();
        OffsetPeer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        OffsetId = buffer.ReadInt32();
        Limit = buffer.ReadInt32();
    }
}
