// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// Get <a href="https://corefork.telegram.org/api/folders">folders</a>
/// <para>See <a href="https://corefork.telegram.org/method/messages.getDialogFilters" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✖] [Anonymous ✖]
/// </remarks>
[TlObject(0xefd48c89)]
public sealed partial class RequestGetDialogFilters : IRequest<MyTelegram.Schema.Messages.IDialogFilters>
{
    public uint ConstructorId => 0xefd48c89;

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
