// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// Use this method to set the score of the specified user in a game sent as an inline message (bots only).
/// <para>Possible errors</para>
/// Code Type Description
/// 400 MESSAGE_ID_INVALID The provided message id is invalid.
/// 400 USER_BOT_REQUIRED This method can only be called by a bot.
/// See <a href="https://corefork.telegram.org/method/messages.setInlineGameScore" />
///</summary>
[TlObject(0x15ad9f64)]
public sealed class RequestSetInlineGameScore : IRequest<IBool>
{
    public uint ConstructorId => 0x15ad9f64;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Set this flag if the game message should be automatically edited to include the current scoreboard
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool EditMessage { get; set; }

    ///<summary>
    /// Set this flag if the high score is allowed to decrease. This can be useful when fixing mistakes or banning cheaters
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Force { get; set; }

    ///<summary>
    /// ID of the inline message
    /// See <a href="https://corefork.telegram.org/type/InputBotInlineMessageID" />
    ///</summary>
    public MyTelegram.Schema.IInputBotInlineMessageID Id { get; set; }

    ///<summary>
    /// User identifier
    /// See <a href="https://corefork.telegram.org/type/InputUser" />
    ///</summary>
    public MyTelegram.Schema.IInputUser UserId { get; set; }

    ///<summary>
    /// New score
    ///</summary>
    public int Score { get; set; }

    public void ComputeFlag()
    {
        if (EditMessage) { Flags[0] = true; }
        if (Force) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
        writer.Write(UserId);
        writer.Write(Score);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { EditMessage = true; }
        if (Flags[1]) { Force = true; }
        Id = reader.Read<MyTelegram.Schema.IInputBotInlineMessageID>();
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
        Score = reader.ReadInt32();
    }
}
