// <auto-generated />

namespace MyTelegram.Schema.Messages;

///<summary>
/// Mark a specific <a href="https://corefork.telegram.org/api/sponsored-messages">sponsored message »</a> as read
/// See <a href="https://corefork.telegram.org/method/messages.viewSponsoredMessage" />
///</summary>
[TlObject(0x269e3643)]
public sealed class RequestViewSponsoredMessage : IRequest<IBool>
{
    public uint ConstructorId => 0x269e3643;

    ///<summary>
    /// The ad's unique ID.
    ///</summary>
    public ReadOnlyMemory<byte> RandomId { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(RandomId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        RandomId = buffer.ReadBytes();
    }
}
