// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

[TlObject(0xd1435160)]
public sealed class RequestDestroyAuthKey : IRequest<MyTelegram.Schema.IDestroyAuthKeyRes>
{
    public uint ConstructorId => 0xd1435160;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}
