// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// No new stickers were found for the given query
/// <para>See <a href="https://corefork.telegram.org/constructor/messages.stickersNotModified" /></para>
/// </summary>
[TlObject(0xf1749a22)]
public sealed partial class TStickersNotModified : IStickers
{
    public uint ConstructorId => 0xf1749a22;
    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
