// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Represents a json-encoded object
/// See <a href="https://corefork.telegram.org/constructor/dataJSON" />
///</summary>
[TlObject(0x7d748d04)]
public sealed class TDataJSON : IDataJSON
{
    public uint ConstructorId => 0x7d748d04;
    ///<summary>
    /// JSON-encoded object
    ///</summary>
    public string Data { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Data);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Data = reader.ReadString();
    }
}