// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/inputPrivacyValueAllowUsers" />
///</summary>
[TlObject(0x131cc67f)]
public class TInputPrivacyValueAllowUsers : IInputPrivacyRule
{
    public uint ConstructorId => 0x131cc67f;
    public TVector<MyTelegram.Schema.IInputUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Users.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Users = br.Deserialize<TVector<MyTelegram.Schema.IInputUser>>();
    }
}