// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/inputMessagesFilterChatPhotos" />
///</summary>
[TlObject(0x3a20ecb8)]
public class TInputMessagesFilterChatPhotos : IMessagesFilter
{
    public uint ConstructorId => 0x3a20ecb8;


    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}