// <auto-generated />

namespace MyTelegram.Schema.Stories;

///<summary>
/// See <a href="https://corefork.telegram.org/method/stories.getAlbumStories" />
///</summary>
[TlObject(0xac806d61)]
public sealed class RequestGetAlbumStories : IRequest<MyTelegram.Schema.Stories.IStories>
{
    public uint ConstructorId => 0xac806d61;

    ///<summary>
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    ///</summary>
    public MyTelegram.Schema.IInputPeer Peer { get; set; }

    public int AlbumId { get; set; }

    public int Offset { get; set; }

    public int Limit { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(AlbumId);
        writer.Write(Offset);
        writer.Write(Limit);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Peer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        AlbumId = buffer.ReadInt32();
        Offset = buffer.ReadInt32();
        Limit = buffer.ReadInt32();
    }
}
