// <auto-generated />

namespace MyTelegram.Schema.Stories;

///<summary>
/// See <a href="https://corefork.telegram.org/method/stories.getAlbums" />
///</summary>
[TlObject(0x25b3eac7)]
public sealed class RequestGetAlbums : IRequest<MyTelegram.Schema.Stories.IAlbums>
{
    public uint ConstructorId => 0x25b3eac7;

    ///<summary>
    /// See <a href="https://corefork.telegram.org/type/InputPeer" />
    ///</summary>
    public MyTelegram.Schema.IInputPeer Peer { get; set; }

    public long Hash { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(Hash);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Peer = buffer.Read<MyTelegram.Schema.IInputPeer>();
        Hash = buffer.ReadInt64();
    }
}
