// <auto-generated />

namespace MyTelegram.Schema.Help;

///<summary>
/// Info about pinned MTProxy or Public Service Announcement peers.
/// See <a href="https://corefork.telegram.org/type/help.PromoData" />
///</summary>
[JsonDerivedType(typeof(TPromoDataEmpty), nameof(TPromoDataEmpty))]
[JsonDerivedType(typeof(TPromoData), nameof(TPromoData))]
public interface IPromoData : IObject
{
    ///<summary>
    /// Re-fetch PSA/MTProxy info after the specified number of seconds
    ///</summary>
    int Expires { get; set; }
}
