// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Defines a GeoPoint by its coordinates.
/// See <a href="https://corefork.telegram.org/constructor/inputGeoPoint" />
///</summary>
[TlObject(0x48222faf)]
public sealed class TInputGeoPoint : IInputGeoPoint
{
    public uint ConstructorId => 0x48222faf;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Latitude
    ///</summary>
    public double Lat { get; set; }

    ///<summary>
    /// Longitude
    ///</summary>
    public double Long { get; set; }

    ///<summary>
    /// The estimated horizontal accuracy of the location, in meters; as defined by the sender.
    ///</summary>
    public int? AccuracyRadius { get; set; }

    public void ComputeFlag()
    {
        if (/*AccuracyRadius != 0 && */AccuracyRadius.HasValue) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Lat);
        writer.Write(Long);
        if (Flags[0]) { writer.Write(AccuracyRadius.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Lat = reader.ReadDouble();
        Long = reader.ReadDouble();
        if (Flags[0]) { AccuracyRadius = reader.ReadInt32(); }
    }
}