// <auto-generated />

namespace MyTelegram.Schema.Phone;

/// <summary>
/// RTMP URL and stream key to be used in streaming software
/// <para>See <a href="https://corefork.telegram.org/type/phone.GroupCallStreamRtmpUrl" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TGroupCallStreamRtmpUrl"/> See <a href="https://corefork.telegram.org/constructor/phone.groupCallStreamRtmpUrl" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TGroupCallStreamRtmpUrl), nameof(TGroupCallStreamRtmpUrl))]
public interface IGroupCallStreamRtmpUrl : IObject
{
    /// <summary>
    /// RTMP URL
    /// </summary>
    string Url { get; set; }

    /// <summary>
    /// Stream key
    /// </summary>
    string Key { get; set; }
}
