// <auto-generated />

namespace MyTelegram.Schema.Help;

/// <summary>
/// An update is available for the application.
/// <para>See <a href="https://corefork.telegram.org/constructor/help.appUpdate" /></para>
/// </summary>
[TlObject(0xccbbce30)]
public sealed partial class TAppUpdate : IAppUpdate
{
    public uint ConstructorId => 0xccbbce30;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// Unskippable, the new info must be shown to the user (with a popup or something else)
    /// </summary>
    public bool CanNotSkip { get; set; }

    /// <summary>
    /// Update ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// New version name
    /// </summary>
    public string Version { get; set; }

    /// <summary>
    /// Text description of the update
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// <a href="https://corefork.telegram.org/api/entities">Message entities for styled text</a>
    /// See <a href="https://corefork.telegram.org/type/MessageEntity" />
    /// </summary>
    public TVector<MyTelegram.Schema.IMessageEntity> Entities { get; set; }

    /// <summary>
    /// Application binary
    /// See <a href="https://corefork.telegram.org/type/Document" />
    /// </summary>
    public MyTelegram.Schema.IDocument? Document { get; set; }

    /// <summary>
    /// Application download URL
    /// </summary>
    public string? Url { get; set; }

    /// <summary>
    /// Associated sticker
    /// See <a href="https://corefork.telegram.org/type/Document" />
    /// </summary>
    public MyTelegram.Schema.IDocument? Sticker { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (CanNotSkip) { flags = flags.SetBit(0); }
        if (Document != null) { flags = flags.SetBit(1); }
        if (Url != null) { flags = flags.SetBit(2); }
        if (Sticker != null) { flags = flags.SetBit(3); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        writer.Write(Id);
        writer.Write(Version);
        writer.Write(Text);
        writer.Write(Entities);
        if (flags.IsBitSet(1)) { writer.Write(Document); }
        if (flags.IsBitSet(2)) { writer.Write(Url); }
        if (flags.IsBitSet(3)) { writer.Write(Sticker); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { CanNotSkip = true; }
        Id = buffer.ReadInt32();
        Version = buffer.ReadString();
        Text = buffer.ReadString();
        Entities = buffer.Read<TVector<MyTelegram.Schema.IMessageEntity>>();
        if (Flags.IsBitSet(1)) { Document = buffer.Read<MyTelegram.Schema.IDocument>(); }
        if (Flags.IsBitSet(2)) { Url = buffer.ReadString(); }
        if (Flags.IsBitSet(3)) { Sticker = buffer.Read<MyTelegram.Schema.IDocument>(); }
    }
}
