// <auto-generated />

namespace MyTelegram.Schema.Help;

/// <summary>
/// Contains info about a <a href="https://corefork.telegram.org/api/colors">color palette »</a>.
/// <para>See <a href="https://corefork.telegram.org/constructor/help.peerColorOption" /></para>
/// </summary>
[TlObject(0xadec6ebe)]
public sealed partial class TPeerColorOption : IPeerColorOption
{
    public uint ConstructorId => 0xadec6ebe;
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    public int Flags { get; set; }

    /// <summary>
    /// Whether this palette should not be displayed as an option to the user when choosing a palette to apply to profile pages or message accents.
    /// </summary>
    public bool Hidden { get; set; }

    /// <summary>
    /// Palette ID.
    /// </summary>
    public int ColorId { get; set; }

    /// <summary>
    /// Light mode palette. <br/>Will be empty for IDs <code>0</code> to <code>6</code> inclusive, in which case a palette containing a single color from the following colors should be used: red, orange, violet, green, cyan, blue, pink for indexes 0 to 6 (i.e. the same colors used for randomized fallback <a href="https://corefork.telegram.org/api/colors">message accent colors</a>).
    /// See <a href="https://corefork.telegram.org/type/help.PeerColorSet" />
    /// </summary>
    public MyTelegram.Schema.Help.IPeerColorSet? Colors { get; set; }

    /// <summary>
    /// Dark mode palette. Optional, defaults to the palette in <code>colors</code> (or the autogenerated palette for IDs <code>0</code> to <code>6</code>) if absent.
    /// See <a href="https://corefork.telegram.org/type/help.PeerColorSet" />
    /// </summary>
    public MyTelegram.Schema.Help.IPeerColorSet? DarkColors { get; set; }

    /// <summary>
    /// Channels can use this palette only after reaching at least the <a href="https://corefork.telegram.org/api/boost">boost level</a> specified in this field.
    /// </summary>
    public int? ChannelMinLevel { get; set; }

    /// <summary>
    /// Supergroups can use this palette only after reaching at least the <a href="https://corefork.telegram.org/api/boost">boost level</a> specified in this field.
    /// </summary>
    public int? GroupMinLevel { get; set; }

    public int CalculateFlags()
    {
        var flags = 0;
        if (Hidden) { flags = flags.SetBit(0); }
        if (Colors != null) { flags = flags.SetBit(1); }
        if (DarkColors != null) { flags = flags.SetBit(2); }
        if (/*ChannelMinLevel != 0 && */ChannelMinLevel.HasValue) { flags = flags.SetBit(3); }
        if (/*GroupMinLevel != 0 && */GroupMinLevel.HasValue) { flags = flags.SetBit(4); }
        return flags;
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        var flags = CalculateFlags();
        writer.Write(ConstructorId);
        writer.Write(flags);
        writer.Write(ColorId);
        if (flags.IsBitSet(1)) { writer.Write(Colors); }
        if (flags.IsBitSet(2)) { writer.Write(DarkColors); }
        if (flags.IsBitSet(3)) { writer.Write(ChannelMinLevel.Value); }
        if (flags.IsBitSet(4)) { writer.Write(GroupMinLevel.Value); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { Hidden = true; }
        ColorId = buffer.ReadInt32();
        if (Flags.IsBitSet(1)) { Colors = buffer.Read<MyTelegram.Schema.Help.IPeerColorSet>(); }
        if (Flags.IsBitSet(2)) { DarkColors = buffer.Read<MyTelegram.Schema.Help.IPeerColorSet>(); }
        if (Flags.IsBitSet(3)) { ChannelMinLevel = buffer.ReadInt32(); }
        if (Flags.IsBitSet(4)) { GroupMinLevel = buffer.ReadInt32(); }
    }
}
