// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// The phone call was missed
/// See <a href="https://corefork.telegram.org/constructor/phoneCallDiscardReasonMissed" />
///</summary>
[TlObject(0x85e42301)]
public sealed class TPhoneCallDiscardReasonMissed : IPhoneCallDiscardReason
{
    public uint ConstructorId => 0x85e42301;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}