// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
///See <a href="https://core.telegram.org/method/messages.sendScreenshotNotification" />
///</summary>
[TlObject(0xc97df020)]
public sealed class RequestSendScreenshotNotification : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xc97df020;

    ///<summary>
    ///See <a href="https://core.telegram.org/type/InputPeer" />
    ///</summary>
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public int ReplyToMsgId { get; set; }
    public long RandomId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Peer.Serialize(bw);
        bw.Write(ReplyToMsgId);
        bw.Write(RandomId);
    }

    public void Deserialize(BinaryReader br)
    {
        Peer = br.Deserialize<MyTelegram.Schema.IInputPeer>();
        ReplyToMsgId = br.ReadInt32();
        RandomId = br.ReadInt64();
    }
}
