// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;


///<summary>
///See <a href="https://core.telegram.org/constructor/messages.availableReactions" />
///</summary>
[TlObject(0x768e3aad)]
public class TAvailableReactions : IAvailableReactions
{
    public uint ConstructorId => 0x768e3aad;
    public int Hash { get; set; }
    public TVector<MyTelegram.Schema.IAvailableReaction> Reactions { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(Hash);
        Reactions.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Hash = br.ReadInt32();
        Reactions = br.Deserialize<TVector<MyTelegram.Schema.IAvailableReaction>>();
    }
}