// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;


///<summary>
///See <a href="https://core.telegram.org/constructor/messages.chatInviteImporters" />
///</summary>
[TlObject(0x81b6b00a)]
public class TChatInviteImporters : IChatInviteImporters
{
    public uint ConstructorId => 0x81b6b00a;
    public int Count { get; set; }
    public TVector<MyTelegram.Schema.IChatInviteImporter> Importers { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(Count);
        Importers.Serialize(bw);
        Users.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Count = br.ReadInt32();
        Importers = br.Deserialize<TVector<MyTelegram.Schema.IChatInviteImporter>>();
        Users = br.Deserialize<TVector<MyTelegram.Schema.IUser>>();
    }
}