// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Photos;


///<summary>
///See <a href="https://core.telegram.org/constructor/photos.photo" />
///</summary>
[TlObject(0x20212ca8)]
public class TPhoto : IPhoto
{
    public uint ConstructorId => 0x20212ca8;

    ///<summary>
    ///See <a href="https://core.telegram.org/type/Photo" />
    ///</summary>
    public MyTelegram.Schema.IPhoto Photo { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Photo.Serialize(bw);
        Users.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Photo = br.Deserialize<MyTelegram.Schema.IPhoto>();
        Users = br.Deserialize<TVector<MyTelegram.Schema.IUser>>();
    }
}