// <auto-generated />

namespace MyTelegram.Schema.Contacts;

///<summary>
/// Delete contacts by phone number
/// See <a href="https://corefork.telegram.org/method/contacts.deleteByPhones" />
///</summary>
[TlObject(0x1013fd9e)]
public sealed class RequestDeleteByPhones : IRequest<IBool>
{
    public uint ConstructorId => 0x1013fd9e;

    ///<summary>
    /// Phone numbers
    ///</summary>
    public TVector<string> Phones { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Phones);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Phones = buffer.Read<TVector<string>>();
    }
}
