// <auto-generated />

namespace MyTelegram.Schema.Bots;

/// <summary>
/// Sends a custom request; for bots only
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 DATA_JSON_INVALID The provided JSON data is invalid.</c></para>
/// <para><c>400 METHOD_INVALID The specified method is invalid.</c></para>
/// <para><c>400 USER_BOT_REQUIRED This method can only be called by a bot. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/bots.sendCustomRequest" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✖] [Bot ✔] [Anonymous ✖]
/// </remarks>
[TlObject(0xaa2769ed)]
public sealed partial class RequestSendCustomRequest : IRequest<MyTelegram.Schema.IDataJSON>
{
    public uint ConstructorId => 0xaa2769ed;

    /// <summary>
    /// The method name
    /// </summary>
    public string CustomMethod { get; set; }

    /// <summary>
    /// JSON-serialized method parameters
    /// See <a href="https://corefork.telegram.org/type/DataJSON" />
    /// </summary>
    public MyTelegram.Schema.IDataJSON Params { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(CustomMethod);
        writer.Write(Params);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        CustomMethod = buffer.ReadString();
        Params = buffer.Read<MyTelegram.Schema.IDataJSON>();
    }
}
