namespace MyTelegram;

public record AdminLogEventActionData(string NewValue, string? PrevValue = null);

public enum AdminLogEventAction
{
    All = 0,
    ChangeAbout = 1,
    ChangeAvailableReactions = 2,
    ChangeHistoryTTL = 3,
    ChangeLinkedChat = 4,
    ChangeLocation = 5,
    ChangePhoto = 6,
    ChangeStickerSet = 7,
    ChangeTitle = 8,
    ChangeUsername = 9,
    DefaultBannedRights = 10,
    DeleteMessage = 11,
    DiscardGroupCall = 12,
    EditMessage = 13,
    ExportedInviteDelete = 14,
    ExportedInviteEdit = 15,
    ExportedInviteRevoke = 16,
    ParticipantInvite = 17,
    ParticipantJoin = 18,
    ParticipantJoinByInvite = 19,
    ParticipantJoinByRequest = 20,
    ParticipantLeave = 21,
    ParticipantMute = 22,
    ParticipantToggleAdmin = 23,
    ParticipantToggleBan = 24,
    ParticipantUnmute = 25,
    ParticipantVolume = 26,
    SendMessage = 27,
    StartGroupCall = 28,
    StopPoll = 29,
    ToggleGroupCallSetting = 30,
    ToggleInvites = 31,
    ToggleNoForwards = 32,
    TogglePreHistoryHidden = 33,
    ToggleSignatures = 34,
    ToggleSlowMode = 35,
    PinnedMessage = 36,
    ToggleSignatureProfiles = 37,
    UnpinMessage = 38,
    ToggleAutotranslation = 39,
    EditRank = 40,
    ChangeEmojiStatus = 41,
    ChangeEmojiStickerSet = 42,
}