namespace MyTelegram;

public enum MessageActionType
{
    None = 0,
    Empty = 1,
    BotAllowed = 2,
    ChannelCreate = 3,
    ChannelMigrateFrom = 4,
    ChatAddUser = 5,
    ChatCreate = 6,
    ChatDeletePhoto = 7,
    ChatDeleteUser = 8,
    ChatEditPhoto = 9,
    ChatEditTitle = 10,
    ChatJoinedByLink = 11,
    ChatMigrateTo = 12,
    ContactSignUp = 13,
    CustomAction = 14,
    GameScore = 15,
    GeoProximityReached = 16,
    GroupCall = 17,
    HistoryClear = 18,
    InviteToGroupCall = 19,
    PaymentSent = 20,
    PaymentSentMe = 21,
    PhoneCall = 22,
    PinMessage = 23,
    ScreenShotTaken = 24,
    SecureValuesSent = 25,
    SecureValuesSentMe = 26,
    SetMessagesTtl = 27,
    ChannelAddUser = 28,
    ForumTopicCreated = 29,
    ForumTopicEdited = 30,
    SetChatWallPaper = 31,
    SetChatTheme = 32,
    CreateQuickReplyMessage = 33,
    ChatJoinBySelf = 34,
    ChatJoinByRequest = 35,
    PaidMessagesPriceUpdated = 36,
    ToggleTodoCompletion = 37,
    ToggleSuggestedPostApproval = 38,
    UpgradeStarGift = 39,
    ResellGiftPurchase = 40,
}