<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MyTelegram</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\MyTelegram.Abstractions\MyTelegram.Abstractions.csproj" />
      <ProjectReference Include="..\MyTelegram.Schema\MyTelegram.Schema.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="Fody">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
