// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/notificationSoundRingtone" />
///</summary>
[TlObject(0xff6c8049)]
public class TNotificationSoundRingtone : INotificationSound
{
    public uint ConstructorId => 0xff6c8049;
    public long Id { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(Id);
    }

    public void Deserialize(BinaryReader br)
    {
        Id = br.ReadInt64();
    }
}