// <auto-generated />

using MyTelegram.Schema.Payments;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarGiftCollections" />
///</summary>
internal sealed class GetStarGiftCollectionsHandler : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestGetStarGiftCollections, MyTelegram.Schema.Payments.IStarGiftCollections>, IObjectHandler
{
    protected override Task<MyTelegram.Schema.Payments.IStarGiftCollections> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestGetStarGiftCollections obj)
    {
        return Task.FromResult<IStarGiftCollections>(new TStarGiftCollections
        {
            Collections = []
        });
    }
}

