// <auto-generated />

namespace MyTelegram.Schema.Upload;

/// <summary>
/// Saves a part of file for further sending to one of the methods.
/// <para><c>Possible errors</c></para>
/// <para><c>Code Type Description</c></para>
/// <para><c>400 FILE_PART_EMPTY The provided file part is empty.</c></para>
/// <para><c>400 FILE_PART_INVALID The file part number is invalid.</c></para>
/// <para><c>400 MSG_ID_INVALID Invalid message ID provided. </c></para>
/// <para>See <a href="https://corefork.telegram.org/method/upload.saveFilePart" /></para>
/// </summary>
/// <remarks>
/// Access: [User ✔] [Bot ✔] [Anonymous ✖]
/// </remarks>
[TlObject(0xb304a621)]
public sealed partial class RequestSaveFilePart : IRequest<IBool>
{
    public uint ConstructorId => 0xb304a621;

    /// <summary>
    /// Random file identifier created by the client
    /// </summary>
    public long FileId { get; set; }

    /// <summary>
    /// Numerical order of a part
    /// </summary>
    public int FilePart { get; set; }

    /// <summary>
    /// Binary data, content of a part
    /// </summary>
    public ReadOnlyMemory<byte> Bytes { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(FileId);
        writer.Write(FilePart);
        writer.Write(Bytes);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        FileId = buffer.ReadInt64();
        FilePart = buffer.ReadInt32();
        Bytes = buffer.ReadBytes();
    }
}
