// <auto-generated/>
// ReSharper disable All
using System.Text.Json.Serialization;

namespace MyTelegram.Services.NativeAot;

#if !DEBUG

// Count:70
// MyTelegram.Core
[JsonSerializable(typeof(MyTelegram.Core.AcksDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.AppCodeCreatedIntegrationEvent))]
[JsonSerializable(typeof(MyTelegram.Core.AuthCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.AuthKeyCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.AuthKeyCreatedIntegrationEvent))]
[JsonSerializable(typeof(MyTelegram.Core.AuthKeyNotFoundEvent))]
[JsonSerializable(typeof(MyTelegram.Core.AuthKeyUnRegisteredIntegrationEvent))]
[JsonSerializable(typeof(MyTelegram.Core.AuthorizationCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.BindUserIdToAuthKeyIntegrationEvent))]
[JsonSerializable(typeof(MyTelegram.Core.BindUserIdToAuthKeySuccessEvent))]
[JsonSerializable(typeof(MyTelegram.Core.BindUserIdToSessionEvent))]
[JsonSerializable(typeof(MyTelegram.Core.ChannelMemberBannedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.ChannelMemberChangedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.ChatMemberChangedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.ClientDisconnectedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.CreateEncryptedPushMessageEvent))]
[JsonSerializable(typeof(MyTelegram.Core.CreatePushMessageEvent))]
[JsonSerializable(typeof(MyTelegram.Core.DataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.DataResultResponseReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.DataResultResponseWithUserIdReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.DeviceRegisteredEvent))]
[JsonSerializable(typeof(MyTelegram.Core.DomainEventMessage))]
[JsonSerializable(typeof(MyTelegram.Core.DownloadDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.DuplicateCommandEvent))]
[JsonSerializable(typeof(MyTelegram.Core.FileDataResultResponseReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.FutureAuthTokenCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.FutureSaltCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.GlobalPrivacySettingsCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.ISessionMessage))]
[JsonSerializable(typeof(MyTelegram.Core.LayeredAuthKeyIdMessageCreatedIntegrationEvent))]
[JsonSerializable(typeof(MyTelegram.Core.LayeredPushMessageCreatedIntegrationEvent))]
[JsonSerializable(typeof(MyTelegram.Core.MessengerCommandDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.MessengerDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.MessengerQueryDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.MtpMessage))]
[JsonSerializable(typeof(MyTelegram.Core.NewDeviceCreatedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.NewPtsMessageHasSentEvent))]
[JsonSerializable(typeof(MyTelegram.Core.NewQtsMessageHasSentEvent))]
[JsonSerializable(typeof(MyTelegram.Core.PhoneCallDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.PingTimeoutEvent))]
[JsonSerializable(typeof(MyTelegram.Core.PushDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.PushMessageToPeerEvent))]
[JsonSerializable(typeof(MyTelegram.Core.PushNotificationCreatedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.RpcMessageHasSentEvent))]
[JsonSerializable(typeof(MyTelegram.Core.SessionPasswordStateChangedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.SessionRevokedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.SetSessionPasswordStateEvent))]
[JsonSerializable(typeof(MyTelegram.Core.StickerDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.TakeoutCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.TransportErrorEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UnRegisterAuthKeyEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UpdatesDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UploadDataReceivedEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UserCacheItem))]
[JsonSerializable(typeof(MyTelegram.Core.UserIsOnlineEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UserLoggedOutEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UserSignInSuccessEvent))]
[JsonSerializable(typeof(MyTelegram.Core.UserSignUpSuccessIntegrationEvent))]

// MyTelegram.Domain.Shared
[JsonSerializable(typeof(MyTelegram.MessageReply))]
[JsonSerializable(typeof(MyTelegram.Peer))]
[JsonSerializable(typeof(MyTelegram.PeerColor))]
[JsonSerializable(typeof(MyTelegram.PhotoSize))]
[JsonSerializable(typeof(MyTelegram.VideoSize))]
[JsonSerializable(typeof(MyTelegram.VideoSizeEmojiMarkup))]
[JsonSerializable(typeof(MyTelegram.WallPaperSettings))]

// EventFlow
[JsonSerializable(typeof(MyTelegram.Peer))]
[JsonSerializable(typeof(MyTelegram.RequestInfo))]
[JsonSerializable(typeof(MyTelegram.Core.UserCacheItem))]
[JsonSerializable(typeof(MyTelegram.Services.Services.AckCacheItem))]
[JsonSerializable(typeof(MyTelegram.Services.Services.PtsCacheItem))]

[JsonSerializable(typeof(global::EventFlow.Aggregates.Metadata))]
[JsonSerializable(typeof(global::EventFlow.Provided.Jobs.DispatchToAsynchronousEventSubscribersJob))]
[JsonSerializable(typeof(global::EventFlow.Snapshots.SnapshotMetadata))]
[JsonSerializable(typeof(System.Collections.Generic.List<PhotoSize>))]
[JsonSerializable(typeof(System.Collections.Generic.List<VideoSize>))]
[JsonSerializable(typeof(System.Collections.Generic.List<FutureAuthTokenCacheItem>))]
#endif
[JsonSerializable(typeof(System.Collections.Generic.List<FutureSaltCacheItem>))]

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public partial class MyJsonSerializeContext : JsonSerializerContext
{
}
