// <auto-generated />

namespace MyTelegram.Schema.Payments;

/// <summary>
/// Contains the URL to use to <a href="https://corefork.telegram.org/api/stars#withdrawing-revenue">withdraw Telegram Star revenue</a>.
/// <para>See <a href="https://corefork.telegram.org/constructor/payments.starsRevenueWithdrawalUrl" /></para>
/// </summary>
[TlObject(0x1dab80b7)]
public sealed partial class TStarsRevenueWithdrawalUrl : IStarsRevenueWithdrawalUrl
{
    public uint ConstructorId => 0x1dab80b7;
    /// <summary>
    /// Contains the URL to use to <a href="https://corefork.telegram.org/api/stars#withdrawing-revenue">withdraw Telegram Star revenue</a>.
    /// </summary>
    public string Url { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Url);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Url = buffer.ReadString();
    }
}
