// <auto-generated />

namespace MyTelegram.Schema.Payments;

/// <summary>
/// <para>See <a href="https://corefork.telegram.org/constructor/payments.starGiftActiveAuctions" /></para>
/// </summary>
[TlObject(0xaef6abbc)]
public sealed partial class TStarGiftActiveAuctions : IStarGiftActiveAuctions
{
    public uint ConstructorId => 0xaef6abbc;
    /// <summary>
    ///  
    /// See <a href="https://corefork.telegram.org/type/StarGiftActiveAuctionState" />
    /// </summary>
    public TVector<MyTelegram.Schema.IStarGiftActiveAuctionState> Auctions { get; set; }

    /// <summary>
    ///  
    /// See <a href="https://corefork.telegram.org/type/User" />
    /// </summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    /// <summary>
    ///  
    /// See <a href="https://corefork.telegram.org/type/Chat" />
    /// </summary>
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Auctions);
        writer.Write(Users);
        writer.Write(Chats);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Auctions = buffer.Read<TVector<MyTelegram.Schema.IStarGiftActiveAuctionState>>();
        Users = buffer.Read<TVector<MyTelegram.Schema.IUser>>();
        Chats = buffer.Read<TVector<MyTelegram.Schema.IChat>>();
    }
}
