// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionGiveawayResults" />
///</summary>
[TlObject(0x2a9fadc5)]
public sealed class TMessageActionGiveawayResults : IMessageAction
{
    public uint ConstructorId => 0x2a9fadc5;
    ///<summary>
    /// &nbsp;
    ///</summary>
    public int WinnersCount { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int UnclaimedCount { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(WinnersCount);
        writer.Write(UnclaimedCount);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        WinnersCount = reader.ReadInt32();
        UnclaimedCount = reader.ReadInt32();
    }
}