// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Auth;

///<summary>
///See <a href="https://core.telegram.org/method/auth.requestPasswordRecovery" />
///</summary>
[TlObject(0xd897bc66)]
public sealed class RequestRequestPasswordRecovery : IRequest<MyTelegram.Schema.Auth.IPasswordRecovery>
{
    public uint ConstructorId => 0xd897bc66;

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}
