// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Auth;

///<summary>
///See <a href="https://core.telegram.org/method/auth.importBotAuthorization" />
///</summary>
[TlObject(0x67a3ff2c)]
public sealed class RequestImportBotAuthorization : IRequest<MyTelegram.Schema.Auth.IAuthorization>
{
    public uint ConstructorId => 0x67a3ff2c;
    public int Flags { get; set; }
    public int ApiId { get; set; }
    public string ApiHash { get; set; }
    public string BotAuthToken { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(Flags);
        bw.Write(ApiId);
        bw.Serialize(ApiHash);
        bw.Serialize(BotAuthToken);
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.ReadInt32();
        ApiId = br.ReadInt32();
        ApiHash = br.Deserialize<string>();
        BotAuthToken = br.Deserialize<string>();
    }
}
