// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/documentAttributeAnimated" />
///</summary>
[TlObject(0x11b58939)]
public class TDocumentAttributeAnimated : IDocumentAttribute
{
    public uint ConstructorId => 0x11b58939;


    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}