// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Document location (video, voice, audio, basically every type except photo)
/// See <a href="https://corefork.telegram.org/constructor/inputDocumentFileLocation" />
///</summary>
[TlObject(0xbad07584)]
public sealed class TInputDocumentFileLocation : IInputFileLocation
{
    public uint ConstructorId => 0xbad07584;
    ///<summary>
    /// Document ID
    ///</summary>
    public long Id { get; set; }

    ///<summary>
    /// <strong>access_hash</strong> parameter from the <a href="https://corefork.telegram.org/constructor/document">document</a> constructor
    ///</summary>
    public long AccessHash { get; set; }

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/file_reference">File reference</a>
    ///</summary>
    public byte[] FileReference { get; set; }

    ///<summary>
    /// Thumbnail size to download the thumbnail
    ///</summary>
    public string ThumbSize { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Id);
        writer.Write(AccessHash);
        writer.Write(FileReference);
        writer.Write(ThumbSize);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Id = reader.ReadInt64();
        AccessHash = reader.ReadInt64();
        FileReference = reader.ReadBytes();
        ThumbSize = reader.ReadString();
    }
}