// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/secureRequiredType" />
///</summary>
[TlObject(0x829d99da)]
public class TSecureRequiredType : ISecureRequiredType
{
    public uint ConstructorId => 0x829d99da;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool NativeNames { get; set; }
    public bool SelfieRequired { get; set; }
    public bool TranslationRequired { get; set; }

    ///<summary>
    ///See <a href="https://core.telegram.org/type/SecureValueType" />
    ///</summary>
    public MyTelegram.Schema.ISecureValueType Type { get; set; }

    public void ComputeFlag()
    {
        if (NativeNames) { Flags[0] = true; }
        if (SelfieRequired) { Flags[1] = true; }
        if (TranslationRequired) { Flags[2] = true; }

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        Type.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        if (Flags[0]) { NativeNames = true; }
        if (Flags[1]) { SelfieRequired = true; }
        if (Flags[2]) { TranslationRequired = true; }
        Type = br.Deserialize<MyTelegram.Schema.ISecureValueType>();
    }
}