// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Contact status: online / offline.
/// <para>See <a href="https://corefork.telegram.org/type/ContactStatus" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TContactStatus"/> See <a href="https://corefork.telegram.org/constructor/contactStatus" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TContactStatus), nameof(TContactStatus))]
public interface IContactStatus : IObject
{
    /// <summary>
    /// User identifier
    /// </summary>
    long UserId { get; set; }

    /// <summary>
    /// Online status
    /// See <a href="https://corefork.telegram.org/type/UserStatus" />
    /// </summary>
    MyTelegram.Schema.IUserStatus Status { get; set; }
}
