//// <auto-generated />

//namespace MyTelegram.Schema;
///// <summary>
///// Object describes the contents of an encrypted message.
///// <para>See <a href="https://corefork.telegram.org/type/DecryptedMessage" /></para>
///// </summary>
///// <remarks>
///// <para>Implementations:</para>
///// <see cref="MyTelegram.Schema.SecretChat.Layer8.TDecryptedMessage"/> See <a href="https://corefork.telegram.org/constructor/decryptedMessage" /><br/>
///// <see cref="MyTelegram.Schema.SecretChat.Layer8.TDecryptedMessageService"/> See <a href="https://corefork.telegram.org/constructor/decryptedMessageService" /><br/>
///// <see cref="MyTelegram.Schema.SecretChat.Layer17.TDecryptedMessage"/> See <a href="https://corefork.telegram.org/constructor/decryptedMessage" /><br/>
///// <see cref="MyTelegram.Schema.SecretChat.Layer17.TDecryptedMessageService"/> See <a href="https://corefork.telegram.org/constructor/decryptedMessageService" /><br/>
///// <see cref="MyTelegram.Schema.SecretChat.Layer45.TDecryptedMessage"/> See <a href="https://corefork.telegram.org/constructor/decryptedMessage" /><br/>
///// <see cref="MyTelegram.Schema.SecretChat.Layer73.TDecryptedMessage"/> See <a href="https://corefork.telegram.org/constructor/decryptedMessage" /><br/>
///// </remarks>
//[JsonDerivedType(typeof(MyTelegram.Schema.SecretChat.Layer8.TDecryptedMessage), "TDecryptedMessageLayer8")]
//[JsonDerivedType(typeof(MyTelegram.Schema.SecretChat.Layer8.TDecryptedMessageService), "TDecryptedMessageServiceLayer8")]
//[JsonDerivedType(typeof(MyTelegram.Schema.SecretChat.Layer17.TDecryptedMessage), "TDecryptedMessageLayer17")]
//[JsonDerivedType(typeof(MyTelegram.Schema.SecretChat.Layer17.TDecryptedMessageService), "TDecryptedMessageServiceLayer17")]
//[JsonDerivedType(typeof(MyTelegram.Schema.SecretChat.Layer45.TDecryptedMessage), "TDecryptedMessageLayer45")]
//[JsonDerivedType(typeof(MyTelegram.Schema.SecretChat.Layer73.TDecryptedMessage), "TDecryptedMessageLayer73")]
//public partial interface IDecryptedMessage : IObject
//{
//    /// <summary>
//    /// Random message ID, assigned by the message author.<br/>Must be equal to the ID passed to the sending method.
//    /// </summary>
//    long RandomId { get; set; }
//}
