// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Object sets an encrypted chat ID.
/// <para>See <a href="https://corefork.telegram.org/type/InputEncryptedChat" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TInputEncryptedChat"/> See <a href="https://corefork.telegram.org/constructor/inputEncryptedChat" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TInputEncryptedChat), nameof(TInputEncryptedChat))]
public interface IInputEncryptedChat : IObject
{
    /// <summary>
    /// Chat ID
    /// </summary>
    int ChatId { get; set; }

    /// <summary>
    /// Checking sum from constructor <a href="https://corefork.telegram.org/constructor/encryptedChat">encryptedChat</a>, <a href="https://corefork.telegram.org/constructor/encryptedChatWaiting">encryptedChatWaiting</a> or <a href="https://corefork.telegram.org/constructor/encryptedChatRequested">encryptedChatRequested</a>
    /// </summary>
    long AccessHash { get; set; }
}
