// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TInputRichFilePhoto"/> See <a href="" /><br/>
/// <see cref="TInputRichFileDocument"/> See <a href="" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TInputRichFilePhoto), nameof(TInputRichFilePhoto))]
[JsonDerivedType(typeof(TInputRichFileDocument), nameof(TInputRichFileDocument))]
public partial interface IInputRichFile : IObject
{
    string Id { get; set; }
}
