// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Saved payment credentials
/// <para>See <a href="https://corefork.telegram.org/type/PaymentSavedCredentials" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TPaymentSavedCredentialsCard"/> See <a href="https://corefork.telegram.org/constructor/paymentSavedCredentialsCard" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TPaymentSavedCredentialsCard), nameof(TPaymentSavedCredentialsCard))]
public interface IPaymentSavedCredentials : IObject
{
    /// <summary>
    /// Card ID
    /// </summary>
    string Id { get; set; }

    /// <summary>
    /// Title
    /// </summary>
    string Title { get; set; }
}
