// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Indicates a possible answer to a <a href="https://corefork.telegram.org/type/Poll">poll</a>.
/// <para>See <a href="https://corefork.telegram.org/type/PollAnswer" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TPollAnswer"/> See <a href="https://corefork.telegram.org/constructor/pollAnswer" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TPollAnswer), nameof(TPollAnswer))]
public interface IPollAnswer : IObject
{
    /// <summary>
    /// Textual representation of the answer (only <a href="https://corefork.telegram.org/api/premium">Premium</a> users can use <a href="https://corefork.telegram.org/api/custom-emoji">custom emoji entities</a> here).
    /// See <a href="https://corefork.telegram.org/type/TextWithEntities" />
    /// </summary>
    MyTelegram.Schema.ITextWithEntities Text { get; set; }

    /// <summary>
    /// The param that has to be passed to <a href="https://corefork.telegram.org/method/messages.sendVote">messages.sendVote</a>.
    /// </summary>
    string Option { get; set; }
}
