// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Represents a <a href="https://corefork.telegram.org/api/saved-messages">saved message dialog »</a>.
/// <para>See <a href="https://corefork.telegram.org/type/SavedDialog" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TSavedDialog"/> See <a href="https://corefork.telegram.org/constructor/savedDialog" /><br/>
/// <see cref="TMonoForumDialog"/> See <a href="https://corefork.telegram.org/constructor/monoForumDialog" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TSavedDialog), nameof(TSavedDialog))]
[JsonDerivedType(typeof(TMonoForumDialog), nameof(TMonoForumDialog))]
public interface ISavedDialog : IObject
{
    /// <summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    /// </summary>
    int Flags { get; set; }

    /// <summary>
    /// The dialog
    /// See <a href="https://corefork.telegram.org/type/Peer" />
    /// </summary>
    MyTelegram.Schema.IPeer Peer { get; set; }

    /// <summary>
    /// The latest message ID
    /// </summary>
    int TopMessage { get; set; }
}
