// <auto-generated />

namespace MyTelegram.Schema;

///<summary>
/// Object defines a user.
/// See <a href="https://corefork.telegram.org/type/User" />
///</summary>
[JsonDerivedType(typeof(TUserEmpty), nameof(TUserEmpty))]
[JsonDerivedType(typeof(TUser), nameof(TUser))]
public interface IUser : IObject
{
    ///<summary>
    /// User identifier or <code>0</code>
    ///</summary>
    long Id { get; set; }
}
