// <auto-generated />

namespace MyTelegram.Schema;

/// <summary>
/// Remote document
/// <para>See <a href="https://corefork.telegram.org/type/WebDocument" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TWebDocument"/> See <a href="https://corefork.telegram.org/constructor/webDocument" /><br/>
/// <see cref="TWebDocumentNoProxy"/> See <a href="https://corefork.telegram.org/constructor/webDocumentNoProxy" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TWebDocument), nameof(TWebDocument))]
[JsonDerivedType(typeof(TWebDocumentNoProxy), nameof(TWebDocumentNoProxy))]
public interface IWebDocument : IObject
{
    /// <summary>
    /// Document URL
    /// </summary>
    string Url { get; set; }

    /// <summary>
    /// File size
    /// </summary>
    int Size { get; set; }

    /// <summary>
    /// MIME type
    /// </summary>
    string MimeType { get; set; }

    /// <summary>
    /// Attributes for media types
    /// See <a href="https://corefork.telegram.org/type/DocumentAttribute" />
    /// </summary>
    TVector<MyTelegram.Schema.IDocumentAttribute> Attributes { get; set; }
}
