// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Represents the rights of a normal user in a <a href="https://corefork.telegram.org/api/channel">supergroup/channel/chat</a>. In this case, the flags are inverted: if set, a flag <strong>does not allow</strong> a user to do X.
/// See <a href="https://corefork.telegram.org/constructor/chatBannedRights" />
///</summary>
[TlObject(0x9f120418)]
public sealed class TChatBannedRights : IChatBannedRights
{
    public uint ConstructorId => 0x9f120418;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// If set, does not allow a user to view messages in a <a href="https://corefork.telegram.org/api/channel">supergroup/channel/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool ViewMessages { get; set; }

    ///<summary>
    /// If set, does not allow a user to send messages in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendMessages { get; set; }

    ///<summary>
    /// If set, does not allow a user to send any media in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendMedia { get; set; }

    ///<summary>
    /// If set, does not allow a user to send stickers in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendStickers { get; set; }

    ///<summary>
    /// If set, does not allow a user to send gifs in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendGifs { get; set; }

    ///<summary>
    /// If set, does not allow a user to send games in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendGames { get; set; }

    ///<summary>
    /// If set, does not allow a user to use inline bots in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendInline { get; set; }

    ///<summary>
    /// If set, does not allow a user to embed links in the messages of a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool EmbedLinks { get; set; }

    ///<summary>
    /// If set, does not allow a user to send polls in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendPolls { get; set; }

    ///<summary>
    /// If set, does not allow any user to change the description of a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool ChangeInfo { get; set; }

    ///<summary>
    /// If set, does not allow any user to invite users in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool InviteUsers { get; set; }

    ///<summary>
    /// If set, does not allow any user to pin messages in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool PinMessages { get; set; }

    ///<summary>
    /// If set, does not allow any user to create, delete or modify <a href="https://corefork.telegram.org/api/forum#forum-topics">forum topics »</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool ManageTopics { get; set; }

    ///<summary>
    /// If set, does not allow a user to send photos in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendPhotos { get; set; }

    ///<summary>
    /// If set, does not allow a user to send videos in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendVideos { get; set; }

    ///<summary>
    /// If set, does not allow a user to send round videos in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendRoundvideos { get; set; }

    ///<summary>
    /// If set, does not allow a user to send audio files in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendAudios { get; set; }

    ///<summary>
    /// If set, does not allow a user to send voice messages in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendVoices { get; set; }

    ///<summary>
    /// If set, does not allow a user to send documents in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendDocs { get; set; }

    ///<summary>
    /// If set, does not allow a user to send text messages in a <a href="https://corefork.telegram.org/api/channel">supergroup/chat</a>.
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool SendPlain { get; set; }

    ///<summary>
    /// Validity of said permissions (it is considered forever any value less then 30 seconds or more then 366 days).
    ///</summary>
    public int UntilDate { get; set; }

    public void ComputeFlag()
    {
        if (ViewMessages) { Flags[0] = true; }
        if (SendMessages) { Flags[1] = true; }
        if (SendMedia) { Flags[2] = true; }
        if (SendStickers) { Flags[3] = true; }
        if (SendGifs) { Flags[4] = true; }
        if (SendGames) { Flags[5] = true; }
        if (SendInline) { Flags[6] = true; }
        if (EmbedLinks) { Flags[7] = true; }
        if (SendPolls) { Flags[8] = true; }
        if (ChangeInfo) { Flags[10] = true; }
        if (InviteUsers) { Flags[15] = true; }
        if (PinMessages) { Flags[17] = true; }
        if (ManageTopics) { Flags[18] = true; }
        if (SendPhotos) { Flags[19] = true; }
        if (SendVideos) { Flags[20] = true; }
        if (SendRoundvideos) { Flags[21] = true; }
        if (SendAudios) { Flags[22] = true; }
        if (SendVoices) { Flags[23] = true; }
        if (SendDocs) { Flags[24] = true; }
        if (SendPlain) { Flags[25] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(UntilDate);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { ViewMessages = true; }
        if (Flags[1]) { SendMessages = true; }
        if (Flags[2]) { SendMedia = true; }
        if (Flags[3]) { SendStickers = true; }
        if (Flags[4]) { SendGifs = true; }
        if (Flags[5]) { SendGames = true; }
        if (Flags[6]) { SendInline = true; }
        if (Flags[7]) { EmbedLinks = true; }
        if (Flags[8]) { SendPolls = true; }
        if (Flags[10]) { ChangeInfo = true; }
        if (Flags[15]) { InviteUsers = true; }
        if (Flags[17]) { PinMessages = true; }
        if (Flags[18]) { ManageTopics = true; }
        if (Flags[19]) { SendPhotos = true; }
        if (Flags[20]) { SendVideos = true; }
        if (Flags[21]) { SendRoundvideos = true; }
        if (Flags[22]) { SendAudios = true; }
        if (Flags[23]) { SendVoices = true; }
        if (Flags[24]) { SendDocs = true; }
        if (Flags[25]) { SendPlain = true; }
        UntilDate = reader.ReadInt32();
    }
}