// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Webpage preview
/// See <a href="https://corefork.telegram.org/constructor/webPage" />
///</summary>
[TlObject(0xe89c45b2)]
public sealed class TWebPage : IWebPage
{
    public uint ConstructorId => 0xe89c45b2;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Preview ID
    ///</summary>
    public long Id { get; set; }

    ///<summary>
    /// URL of previewed webpage
    ///</summary>
    public string Url { get; set; }

    ///<summary>
    /// Webpage URL to be displayed to the user
    ///</summary>
    public string DisplayUrl { get; set; }

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/offsets#hash-generation">Hash for pagination, for more info click here</a>
    ///</summary>
    public int Hash { get; set; }

    ///<summary>
    /// Type of the web page. Can be: article, photo, audio, video, document, profile, app, or something else
    ///</summary>
    public string? Type { get; set; }

    ///<summary>
    /// Short name of the site (e.g., Google Docs, App Store)
    ///</summary>
    public string? SiteName { get; set; }

    ///<summary>
    /// Title of the content
    ///</summary>
    public string? Title { get; set; }

    ///<summary>
    /// Content description
    ///</summary>
    public string? Description { get; set; }

    ///<summary>
    /// Image representing the content
    /// See <a href="https://corefork.telegram.org/type/Photo" />
    ///</summary>
    public MyTelegram.Schema.IPhoto? Photo { get; set; }

    ///<summary>
    /// URL to show in the embedded preview
    ///</summary>
    public string? EmbedUrl { get; set; }

    ///<summary>
    /// MIME type of the embedded preview, (e.g., text/html or video/mp4)
    ///</summary>
    public string? EmbedType { get; set; }

    ///<summary>
    /// Width of the embedded preview
    ///</summary>
    public int? EmbedWidth { get; set; }

    ///<summary>
    /// Height of the embedded preview
    ///</summary>
    public int? EmbedHeight { get; set; }

    ///<summary>
    /// Duration of the content, in seconds
    ///</summary>
    public int? Duration { get; set; }

    ///<summary>
    /// Author of the content
    ///</summary>
    public string? Author { get; set; }

    ///<summary>
    /// Preview of the content as a media file
    /// See <a href="https://corefork.telegram.org/type/Document" />
    ///</summary>
    public MyTelegram.Schema.IDocument? Document { get; set; }

    ///<summary>
    /// Page contents in <a href="https://instantview.telegram.org/">instant view</a> format
    /// See <a href="https://corefork.telegram.org/type/Page" />
    ///</summary>
    public MyTelegram.Schema.IPage? CachedPage { get; set; }

    ///<summary>
    /// Webpage attributes
    ///</summary>
    public TVector<MyTelegram.Schema.IWebPageAttribute>? Attributes { get; set; }

    public void ComputeFlag()
    {
        if (Type != null) { Flags[0] = true; }
        if (SiteName != null) { Flags[1] = true; }
        if (Title != null) { Flags[2] = true; }
        if (Description != null) { Flags[3] = true; }
        if (Photo != null) { Flags[4] = true; }
        if (EmbedUrl != null) { Flags[5] = true; }
        if (EmbedType != null) { Flags[5] = true; }
        if (/*EmbedWidth != 0 && */EmbedWidth.HasValue) { Flags[6] = true; }
        if (/*EmbedHeight != 0 && */EmbedHeight.HasValue) { Flags[6] = true; }
        if (/*Duration != 0 && */Duration.HasValue) { Flags[7] = true; }
        if (Author != null) { Flags[8] = true; }
        if (Document != null) { Flags[9] = true; }
        if (CachedPage != null) { Flags[10] = true; }
        if (Attributes?.Count > 0) { Flags[12] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
        writer.Write(Url);
        writer.Write(DisplayUrl);
        writer.Write(Hash);
        if (Flags[0]) { writer.Write(Type); }
        if (Flags[1]) { writer.Write(SiteName); }
        if (Flags[2]) { writer.Write(Title); }
        if (Flags[3]) { writer.Write(Description); }
        if (Flags[4]) { writer.Write(Photo); }
        if (Flags[5]) { writer.Write(EmbedUrl); }
        if (Flags[5]) { writer.Write(EmbedType); }
        if (Flags[6]) { writer.Write(EmbedWidth.Value); }
        if (Flags[6]) { writer.Write(EmbedHeight.Value); }
        if (Flags[7]) { writer.Write(Duration.Value); }
        if (Flags[8]) { writer.Write(Author); }
        if (Flags[9]) { writer.Write(Document); }
        if (Flags[10]) { writer.Write(CachedPage); }
        if (Flags[12]) { writer.Write(Attributes); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Id = reader.ReadInt64();
        Url = reader.ReadString();
        DisplayUrl = reader.ReadString();
        Hash = reader.ReadInt32();
        if (Flags[0]) { Type = reader.ReadString(); }
        if (Flags[1]) { SiteName = reader.ReadString(); }
        if (Flags[2]) { Title = reader.ReadString(); }
        if (Flags[3]) { Description = reader.ReadString(); }
        if (Flags[4]) { Photo = reader.Read<MyTelegram.Schema.IPhoto>(); }
        if (Flags[5]) { EmbedUrl = reader.ReadString(); }
        if (Flags[5]) { EmbedType = reader.ReadString(); }
        if (Flags[6]) { EmbedWidth = reader.ReadInt32(); }
        if (Flags[6]) { EmbedHeight = reader.ReadInt32(); }
        if (Flags[7]) { Duration = reader.ReadInt32(); }
        if (Flags[8]) { Author = reader.ReadString(); }
        if (Flags[9]) { Document = reader.Read<MyTelegram.Schema.IDocument>(); }
        if (Flags[10]) { CachedPage = reader.Read<MyTelegram.Schema.IPage>(); }
        if (Flags[12]) { Attributes = reader.Read<TVector<MyTelegram.Schema.IWebPageAttribute>>(); }
    }
}