// <auto-generated/>
// ReSharper disable All
namespace MyTelegram.Schema.Help.LayerN;

[TlObject(0xc0e202f7)]
public sealed partial class RequestTest : IRequest<IBool>
{
    public uint ConstructorId => 0xc0e202f7;

    public void Serialize(IBufferWriter<byte> writer)
    {
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        
    }

    public int GetLength()
    {
        return 4;
    }
}
