// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;


///<summary>
///See <a href="https://core.telegram.org/constructor/account.wallPapersNotModified" />
///</summary>
[TlObject(0x1c199183)]
public class TWallPapersNotModified : IWallPapers
{
    public uint ConstructorId => 0x1c199183;


    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}