// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// New member in the group
/// See <a href="https://corefork.telegram.org/constructor/messageActionChatAddUser" />
///</summary>
[TlObject(0x15cefd00)]
public sealed class TMessageActionChatAddUser : IMessageAction
{
    public uint ConstructorId => 0x15cefd00;
    ///<summary>
    /// Users that were invited to the chat
    ///</summary>
    public TVector<long> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Users = reader.Read<TVector<long>>();
    }
}