// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Chatlists;

///<summary>
/// Info about multiple <a href="https://corefork.telegram.org/api/links#chat-folder-links">chat folder deep links »</a>.
/// See <a href="https://corefork.telegram.org/constructor/chatlists.exportedInvites" />
///</summary>
[TlObject(0x10ab6dc7)]
public sealed class TExportedInvites : IExportedInvites
{
    public uint ConstructorId => 0x10ab6dc7;
    ///<summary>
    /// The <a href="https://corefork.telegram.org/api/links#chat-folder-links">chat folder deep links »</a>.
    ///</summary>
    public TVector<MyTelegram.Schema.IExportedChatlistInvite> Invites { get; set; }

    ///<summary>
    /// Related chat information
    ///</summary>
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }

    ///<summary>
    /// Related user information
    ///</summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Invites);
        writer.Write(Chats);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Invites = reader.Read<TVector<MyTelegram.Schema.IExportedChatlistInvite>>();
        Chats = reader.Read<TVector<MyTelegram.Schema.IChat>>();
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}