// <auto-generated />

namespace MyTelegram.Schema.Phone;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// Access: [User ] [Bot ] [Anonymous ]
/// </remarks>
[TlObject(0x6f636302)]
public sealed partial class RequestGetGroupCallStars : IRequest<MyTelegram.Schema.Phone.IGroupCallStars>
{
    public uint ConstructorId => 0x6f636302;

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputGroupCall" />
    /// </summary>
    public MyTelegram.Schema.IInputGroupCall Call { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Call);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Call = buffer.Read<MyTelegram.Schema.IInputGroupCall>();
    }
}
