// <auto-generated />

namespace MyTelegram.Schema.Phone;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// Access: [User ] [Bot ] [Anonymous ]
/// </remarks>
[TlObject(0xf64f54f7)]
public sealed partial class RequestDeleteGroupCallMessages : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xf64f54f7;

    public int Flags { get; set; }

    public bool ReportSpam { get; set; }

    /// <summary>
    /// See <a href="https://corefork.telegram.org/type/InputGroupCall" />
    /// </summary>
    public MyTelegram.Schema.IInputGroupCall Call { get; set; }

    public TVector<int> Messages { get; set; }

    public void ComputeFlag()
    {
        if (ReportSpam) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Call);
        writer.Write(Messages);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { ReportSpam = true; }
        Call = buffer.Read<MyTelegram.Schema.IInputGroupCall>();
        Messages = buffer.Read<TVector<int>>();
    }
}
