// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/inputBotInlineMessageMediaVenue" />
///</summary>
[TlObject(0x417bbf11)]
public sealed class TInputBotInlineMessageMediaVenue : IInputBotInlineMessage
{
    public uint ConstructorId => 0x417bbf11;
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    ///See <a href="https://core.telegram.org/type/InputGeoPoint" />
    ///</summary>
    public MyTelegram.Schema.IInputGeoPoint GeoPoint { get; set; }
    public string Title { get; set; }
    public string Address { get; set; }
    public string Provider { get; set; }
    public string VenueId { get; set; }
    public string VenueType { get; set; }

    ///<summary>
    ///See <a href="https://core.telegram.org/type/ReplyMarkup" />
    ///</summary>
    public MyTelegram.Schema.IReplyMarkup? ReplyMarkup { get; set; }

    public void ComputeFlag()
    {
        if (ReplyMarkup != null) { Flags[2] = true; }
    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        GeoPoint.Serialize(bw);
        bw.Serialize(Title);
        bw.Serialize(Address);
        bw.Serialize(Provider);
        bw.Serialize(VenueId);
        bw.Serialize(VenueType);
        if (Flags[2]) { ReplyMarkup.Serialize(bw); }
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        GeoPoint = br.Deserialize<MyTelegram.Schema.IInputGeoPoint>();
        Title = br.Deserialize<string>();
        Address = br.Deserialize<string>();
        Provider = br.Deserialize<string>();
        VenueId = br.Deserialize<string>();
        VenueType = br.Deserialize<string>();
        if (Flags[2]) { ReplyMarkup = br.Deserialize<MyTelegram.Schema.IReplyMarkup>(); }
    }
}