// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/pageBlockTable" />
///</summary>
[TlObject(0xbf4dea82)]
public sealed class TPageBlockTable : IPageBlock
{
    public uint ConstructorId => 0xbf4dea82;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Bordered { get; set; }
    public bool Striped { get; set; }

    ///<summary>
    ///See <a href="https://core.telegram.org/type/RichText" />
    ///</summary>
    public MyTelegram.Schema.IRichText Title { get; set; }
    public TVector<MyTelegram.Schema.IPageTableRow> Rows { get; set; }

    public void ComputeFlag()
    {
        if (Bordered) { Flags[0] = true; }
        if (Striped) { Flags[1] = true; }

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        Title.Serialize(bw);
        Rows.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        if (Flags[0]) { Bordered = true; }
        if (Flags[1]) { Striped = true; }
        Title = br.Deserialize<MyTelegram.Schema.IRichText>();
        Rows = br.Deserialize<TVector<MyTelegram.Schema.IPageTableRow>>();
    }
}