// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Auth;

///<summary>
/// The code was sent via SMS
/// See <a href="https://corefork.telegram.org/constructor/auth.sentCodeTypeSms" />
///</summary>
[TlObject(0xc000bba2)]
public sealed class TSentCodeTypeSms : ISentCodeType
{
    public uint ConstructorId => 0xc000bba2;
    ///<summary>
    /// Length of the code in bytes
    ///</summary>
    public int Length { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Length);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Length = reader.ReadInt32();
    }
}