// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// The list of favorited stickers was changed, the client should call <a href="https://corefork.telegram.org/method/messages.getFavedStickers">messages.getFavedStickers</a> to refetch the new list
/// See <a href="https://corefork.telegram.org/constructor/updateFavedStickers" />
///</summary>
[TlObject(0xe511996d)]
public sealed class TUpdateFavedStickers : IUpdate
{
    public uint ConstructorId => 0xe511996d;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}