// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/keyboardButtonRequestPoll" />
///</summary>
[TlObject(0xbbc7515d)]
public sealed class TKeyboardButtonRequestPoll : IKeyboardButton
{
    public uint ConstructorId => 0xbbc7515d;
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    ///See <a href="https://core.telegram.org/type/Bool" />
    ///</summary>
    public bool? Quiz { get; set; }
    public string Text { get; set; }

    public void ComputeFlag()
    {
        if (Quiz !=null) { Flags[0] = true; }

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        if (Flags[0]) { bw.Serialize(Quiz.Value); }
        bw.Serialize(Text);
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        if (Flags[0]) { Quiz = br.Deserialize<bool>(); }
        Text = br.Deserialize<string>();
    }
}