// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/keyboardButtonSwitchInline" />
///</summary>
[TlObject(0x93b9fbb5)]
public sealed class TKeyboardButtonSwitchInline : IKeyboardButton
{
    public uint ConstructorId => 0x93b9fbb5;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool SamePeer { get; set; }
    public string Text { get; set; }
    public string Query { get; set; }
    public TVector<MyTelegram.Schema.IInlineQueryPeerType>? PeerTypes { get; set; }

    public void ComputeFlag()
    {
        if (SamePeer) { Flags[0] = true; }
        if (PeerTypes?.Count > 0) { Flags[1] = true; }
    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Flags);
        bw.Serialize(Text);
        bw.Serialize(Query);
        if (Flags[1]) { PeerTypes.Serialize(bw); }
    }

    public void Deserialize(BinaryReader br)
    {
        Flags = br.Deserialize<BitArray>();
        if (Flags[0]) { SamePeer = true; }
        Text = br.Deserialize<string>();
        Query = br.Deserialize<string>();
        if (Flags[1]) { PeerTypes = br.Deserialize<TVector<MyTelegram.Schema.IInlineQueryPeerType>>(); }
    }
}