// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Help;

///<summary>
///See <a href="https://core.telegram.org/method/help.getNearestDc" />
///</summary>
[TlObject(0x1fb33026)]
public sealed class RequestGetNearestDc : IRequest<MyTelegram.Schema.INearestDc>
{
    public uint ConstructorId => 0x1fb33026;

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}
