// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// User is recording a voice message.
/// See <a href="https://corefork.telegram.org/constructor/sendMessageRecordAudioAction" />
///</summary>
[TlObject(0xd52f73f7)]
public sealed class TSendMessageRecordAudioAction : ISendMessageAction
{
    public uint ConstructorId => 0xd52f73f7;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}