// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/keyboardButtonUserProfile" />
///</summary>
[TlObject(0x308660c1)]
public class TKeyboardButtonUserProfile : IKeyboardButton
{
    public uint ConstructorId => 0x308660c1;
    public string Text { get; set; }
    public long UserId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Serialize(Text);
        bw.Write(UserId);
    }

    public void Deserialize(BinaryReader br)
    {
        Text = br.Deserialize<string>();
        UserId = br.ReadInt64();
    }
}