global using EventFlow;
global using EventFlow.Aggregates;
global using EventFlow.EventStores;
global using EventFlow.Extensions;
global using EventFlow.Queries;
global using EventFlow.Subscribers;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using MyTelegram.Abstractions;
global using MyTelegram.Converters.TLObjects.Interfaces;
global using MyTelegram.Core;
global using MyTelegram.Domain;
global using MyTelegram.Domain.Aggregates.Channel;
global using MyTelegram.Domain.Aggregates.Contact;
global using MyTelegram.Domain.Aggregates.Dialog;
global using MyTelegram.Domain.Aggregates.Messaging;
global using MyTelegram.Domain.Aggregates.Pts;
global using MyTelegram.Domain.Aggregates.QrCode;
global using MyTelegram.Domain.Aggregates.RpcResult;
global using MyTelegram.Domain.Aggregates.User;
global using MyTelegram.Domain.Extensions;
global using MyTelegram.Domain.Sagas;
global using MyTelegram.Domain.Sagas.Events;
global using MyTelegram.Domain.Sagas.Identities;
global using MyTelegram.EventBus;
global using MyTelegram.EventBus.RabbitMQ;
global using MyTelegram.EventFlow.Extensions;
global using MyTelegram.EventFlow.MongoDB;
global using MyTelegram.Messenger.Converters.ConverterServices;
global using MyTelegram.Messenger.Converters.ConverterServices.Channels;
global using MyTelegram.Messenger.Converters.ConverterServices.Messages;
global using MyTelegram.Messenger.DomainEventHandlers;
global using MyTelegram.Queries;
global using MyTelegram.ReadModel.Interfaces;
global using MyTelegram.Schema;
global using MyTelegram.Schema.Auth;
global using MyTelegram.Schema.Contacts;
global using MyTelegram.Schema.Messages;
global using MyTelegram.Services.Extensions;
global using MyTelegram.Services.Services;
global using MyTelegram.Services.TLObjectConverters;
global using System.Diagnostics;
global using System.Reflection;
global using System.Threading.Tasks;
global using PtsForAuthKeyIdReadModel = MyTelegram.ReadModel.MongoDB.PtsForAuthKeyIdReadModel;
global using PtsReadModel = MyTelegram.ReadModel.MongoDB.PtsReadModel;
global using RpcResultReadModel = MyTelegram.ReadModel.MongoDB.RpcResultReadModel;
global using UpdatesReadModel = MyTelegram.ReadModel.MongoDB.UpdatesReadModel;
