// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// No filter
/// See <a href="https://corefork.telegram.org/constructor/channelMessagesFilterEmpty" />
///</summary>
[TlObject(0x94d42ee7)]
public sealed class TChannelMessagesFilterEmpty : IChannelMessagesFilter,IEmpty
{
    public uint ConstructorId => 0x94d42ee7;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {

    }
}