// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// Get <a href="https://instantview.telegram.org/">instant view</a> page
/// <para>Possible errors</para>
/// Code Type Description
/// 400 WC_CONVERT_URL_INVALID WC convert URL invalid.
/// See <a href="https://corefork.telegram.org/method/messages.getWebPage" />
///</summary>
[TlObject(0x32ca8f91)]
public sealed class RequestGetWebPage : IRequest<MyTelegram.Schema.IWebPage>
{
    public uint ConstructorId => 0x32ca8f91;
    ///<summary>
    /// URL of IV page to fetch
    ///</summary>
    public string Url { get; set; }

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/offsets#hash-generation">Hash for pagination, for more info click here</a>
    ///</summary>
    public int Hash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Url);
        writer.Write(Hash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Url = reader.ReadString();
        Hash = reader.ReadInt32();
    }
}
