// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;


///<summary>
///See <a href="https://core.telegram.org/constructor/channels.sendAsPeers" />
///</summary>
[TlObject(0x8356cda9)]
public class TSendAsPeers : ISendAsPeers
{
    public uint ConstructorId => 0x8356cda9;
    public TVector<MyTelegram.Schema.IPeer> Peers { get; set; }
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        Peers.Serialize(bw);
        Chats.Serialize(bw);
        Users.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        Peers = br.Deserialize<TVector<MyTelegram.Schema.IPeer>>();
        Chats = br.Deserialize<TVector<MyTelegram.Schema.IChat>>();
        Users = br.Deserialize<TVector<MyTelegram.Schema.IUser>>();
    }
}