// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


[TlObject(0xae500895)]
public sealed class TFutureSalts : IFutureSalts
{
    public uint ConstructorId => 0xae500895;
    public long ReqMsgId { get; set; }
    public int Now { get; set; }
    public TVector<MyTelegram.Schema.IFutureSalt> Salts { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(ReqMsgId);
        bw.Write(Now);
        Salts.Serialize(bw);
    }

    public void Deserialize(BinaryReader br)
    {
        ReqMsgId = br.ReadInt64();
        Now = br.ReadInt32();
        Salts = br.Deserialize<TVector<MyTelegram.Schema.IFutureSalt>>();
    }
}