// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// <para>See <a href="" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TChatInviteJoinResultOk"/> See <a href="" /><br/>
/// <see cref="TChatInviteJoinResultWebView"/> See <a href="" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TChatInviteJoinResultOk), nameof(TChatInviteJoinResultOk))]
[JsonDerivedType(typeof(TChatInviteJoinResultWebView), nameof(TChatInviteJoinResultWebView))]
public partial interface IChatInviteJoinResult : IObject
{
}
