// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// Object contains list of chats with auxiliary data.
/// <para>See <a href="https://corefork.telegram.org/type/messages.Chats" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TChats"/> See <a href="https://corefork.telegram.org/constructor/messages.chats" /><br/>
/// <see cref="TChatsSlice"/> See <a href="https://corefork.telegram.org/constructor/messages.chatsSlice" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TChats), nameof(TChats))]
[JsonDerivedType(typeof(TChatsSlice), nameof(TChatsSlice))]
public interface IChats : IObject
{
    /// <summary>
    /// List of chats
    /// See <a href="https://corefork.telegram.org/type/Chat" />
    /// </summary>
    TVector<MyTelegram.Schema.IChat> Chats { get; set; }
}
