// <auto-generated />

namespace MyTelegram.Schema.Messages;

/// <summary>
/// Saved GIFs
/// <para>See <a href="https://corefork.telegram.org/type/messages.SavedGifs" /></para>
/// </summary>
/// <remarks>
/// <para>Implementations:</para>
/// <see cref="TSavedGifsNotModified"/> See <a href="https://corefork.telegram.org/constructor/messages.savedGifsNotModified" /><br/>
/// <see cref="TSavedGifs"/> See <a href="https://corefork.telegram.org/constructor/messages.savedGifs" /><br/>
/// </remarks>
[JsonDerivedType(typeof(TSavedGifsNotModified), nameof(TSavedGifsNotModified))]
[JsonDerivedType(typeof(TSavedGifs), nameof(TSavedGifs))]
public interface ISavedGifs : IObject
{
}
