// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/cdnPublicKey" />
///</summary>
[TlObject(0xc982eaba)]
public sealed class TCdnPublicKey : ICdnPublicKey
{
    public uint ConstructorId => 0xc982eaba;
    public int DcId { get; set; }
    public string PublicKey { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(DcId);
        bw.Serialize(PublicKey);
    }

    public void Deserialize(BinaryReader br)
    {
        DcId = br.ReadInt32();
        PublicKey = br.Deserialize<string>();
    }
}