// <auto-generated />

namespace MyTelegram.Schema.Users;

/// <summary>
/// List of songs currently pinned on a user's profile, see <a href="https://corefork.telegram.org/api/profile#music">here »</a> for more info.
/// <para>See <a href="https://corefork.telegram.org/constructor/users.savedMusic" /></para>
/// </summary>
[TlObject(0x34a2f297)]
public sealed partial class TSavedMusic : ISavedMusic
{
    public uint ConstructorId => 0x34a2f297;
    /// <summary>
    /// Total number of songs (can be bigger than <code>documents</code> depending on the passed <code>limit</code>, and the default maximum <code>limit</code> in which case pagination is required).
    /// </summary>
    public int Count { get; set; }

    /// <summary>
    /// Songs.
    /// See <a href="https://corefork.telegram.org/type/Document" />
    /// </summary>
    public TVector<MyTelegram.Schema.IDocument> Documents { get; set; }

    public void ComputeFlag()
    {
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Count);
        writer.Write(Documents);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Count = buffer.ReadInt32();
        Documents = buffer.Read<TVector<MyTelegram.Schema.IDocument>>();
    }
}
