// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stories;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/stories.canApplyBoostReplace" />
///</summary>
[TlObject(0x712c4655)]
public sealed class TCanApplyBoostReplace : ICanApplyBoostResult
{
    public uint ConstructorId => 0x712c4655;
    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/Peer" />
    ///</summary>
    public MyTelegram.Schema.IPeer CurrentBoost { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(CurrentBoost);
        writer.Write(Chats);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        CurrentBoost = reader.Read<MyTelegram.Schema.IPeer>();
        Chats = reader.Read<TVector<MyTelegram.Schema.IChat>>();
    }
}