// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// A stickerset was just moved to top, <a href="https://corefork.telegram.org/api/stickers#recent-stickersets">see here for more info »</a>
/// See <a href="https://corefork.telegram.org/constructor/updateMoveStickerSetToTop" />
///</summary>
[TlObject(0x86fccf85)]
public sealed class TUpdateMoveStickerSetToTop : IUpdate
{
    public uint ConstructorId => 0x86fccf85;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// This update is referring to a <a href="https://corefork.telegram.org/api/stickers#mask-stickers">mask stickerset</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Masks { get; set; }

    ///<summary>
    /// This update is referring to a <a href="https://corefork.telegram.org/api/custom-emoji">custom emoji stickerset</a>
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Emojis { get; set; }

    ///<summary>
    /// <a href="https://corefork.telegram.org/api/stickers">Stickerset</a> ID
    ///</summary>
    public long Stickerset { get; set; }

    public void ComputeFlag()
    {
        if (Masks) { Flags[0] = true; }
        if (Emojis) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stickerset);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Masks = true; }
        if (Flags[1]) { Emojis = true; }
        Stickerset = reader.ReadInt64();
    }
}