// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


[TlObject(0x62d350c9)]
public class TDestroySessionNone : IDestroySessionRes
{
    public uint ConstructorId => 0x62d350c9;
    public long SessionId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(SessionId);
    }

    public void Deserialize(BinaryReader br)
    {
        SessionId = br.ReadInt64();
    }
}