// <auto-generated />
namespace MyTelegram.Messenger.Handlers.Auth;
/// <summary>
/// <para><c>See <a href="https://corefork.telegram.org/method/auth.checkPaidAuth"/> </c></para>
/// </summary>
/// <remarks>
/// Access: [User ✖] [Bot ✖] [Anonymous ✖]
/// </remarks>
internal sealed class CheckPaidAuthHandler : RpcResultObjectHandler<MyTelegram.Schema.Auth.RequestCheckPaidAuth, MyTelegram.Schema.Auth.ISentCode>, IObjectHandler
{
    protected override Task<MyTelegram.Schema.Auth.ISentCode> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Auth.RequestCheckPaidAuth obj)
    {
        throw new NotImplementedException();
    }
}