// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/updateReadChannelDiscussionOutbox" />
///</summary>
[TlObject(0x695c9e7c)]
public sealed class TUpdateReadChannelDiscussionOutbox : IUpdate
{
    public uint ConstructorId => 0x695c9e7c;
    public long ChannelId { get; set; }
    public int TopMsgId { get; set; }
    public int ReadMaxId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(ChannelId);
        bw.Write(TopMsgId);
        bw.Write(ReadMaxId);
    }

    public void Deserialize(BinaryReader br)
    {
        ChannelId = br.ReadInt64();
        TopMsgId = br.ReadInt32();
        ReadMaxId = br.ReadInt32();
    }
}