// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/updateChatParticipantAdd" />
///</summary>
[TlObject(0x3dda5451)]
public sealed class TUpdateChatParticipantAdd : IUpdate
{
    public uint ConstructorId => 0x3dda5451;
    public long ChatId { get; set; }
    public long UserId { get; set; }
    public long InviterId { get; set; }
    public int Date { get; set; }
    public int Version { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);
        bw.Write(ChatId);
        bw.Write(UserId);
        bw.Write(InviterId);
        bw.Write(Date);
        bw.Write(Version);
    }

    public void Deserialize(BinaryReader br)
    {
        ChatId = br.ReadInt64();
        UserId = br.ReadInt64();
        InviterId = br.ReadInt64();
        Date = br.ReadInt32();
        Version = br.ReadInt32();
    }
}