// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/updateAttachMenuBots" />
///</summary>
[TlObject(0x17b7a20b)]
public sealed class TUpdateAttachMenuBots : IUpdate
{
    public uint ConstructorId => 0x17b7a20b;


    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}