// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


///<summary>
///See <a href="https://core.telegram.org/constructor/updateSavedRingtones" />
///</summary>
[TlObject(0x74d8be99)]
public sealed class TUpdateSavedRingtones : IUpdate
{
    public uint ConstructorId => 0x74d8be99;


    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}