// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;


[TlObject(0xea109b13)]
public sealed class TDestroyAuthKeyFail : IDestroyAuthKeyRes
{
    public uint ConstructorId => 0xea109b13;


    public void ComputeFlag()
    {

    }

    public void Serialize(BinaryWriter bw)
    {
        ComputeFlag();
        bw.Write(ConstructorId);

    }

    public void Deserialize(BinaryReader br)
    {

    }
}